# automatically generated by the FlatBuffers compiler, do not modify

# namespace: debug

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DebugPrimitiveModel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DebugPrimitiveModel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDebugPrimitiveModel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DebugPrimitiveModel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DebugPrimitiveModel
    def VertOffset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # DebugPrimitiveModel
    def EboOffset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # DebugPrimitiveModel
    def VertLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # DebugPrimitiveModel
    def EboLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def DebugPrimitiveModelStart(builder):
    builder.StartObject(4)

def Start(builder):
    DebugPrimitiveModelStart(builder)

def DebugPrimitiveModelAddVertOffset(builder, vertOffset):
    builder.PrependUint32Slot(0, vertOffset, 0)

def AddVertOffset(builder, vertOffset):
    DebugPrimitiveModelAddVertOffset(builder, vertOffset)

def DebugPrimitiveModelAddEboOffset(builder, eboOffset):
    builder.PrependUint32Slot(1, eboOffset, 0)

def AddEboOffset(builder, eboOffset):
    DebugPrimitiveModelAddEboOffset(builder, eboOffset)

def DebugPrimitiveModelAddVertLength(builder, vertLength):
    builder.PrependUint32Slot(2, vertLength, 0)

def AddVertLength(builder, vertLength):
    DebugPrimitiveModelAddVertLength(builder, vertLength)

def DebugPrimitiveModelAddEboLength(builder, eboLength):
    builder.PrependUint32Slot(3, eboLength, 0)

def AddEboLength(builder, eboLength):
    DebugPrimitiveModelAddEboLength(builder, eboLength)

def DebugPrimitiveModelEnd(builder):
    return builder.EndObject()

def End(builder):
    return DebugPrimitiveModelEnd(builder)
