# automatically generated by the FlatBuffers compiler, do not modify

# namespace: debug

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DebugPrimitives(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DebugPrimitives()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDebugPrimitives(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DebugPrimitives
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DebugPrimitives
    def ModelNames(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # DebugPrimitives
    def ModelNamesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DebugPrimitives
    def ModelNamesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # DebugPrimitives
    def ModelOffsets(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from gl.debug.DebugPrimitiveModel import DebugPrimitiveModel
            obj = DebugPrimitiveModel()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DebugPrimitives
    def ModelOffsetsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DebugPrimitives
    def ModelOffsetsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # DebugPrimitives
    def Vertices(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from gl.debug.DebugPrimitiveVertex import DebugPrimitiveVertex
            obj = DebugPrimitiveVertex()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DebugPrimitives
    def VerticesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DebugPrimitives
    def VerticesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # DebugPrimitives
    def Indices(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # DebugPrimitives
    def IndicesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # DebugPrimitives
    def IndicesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DebugPrimitives
    def IndicesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def DebugPrimitivesStart(builder):
    builder.StartObject(4)

def Start(builder):
    DebugPrimitivesStart(builder)

def DebugPrimitivesAddModelNames(builder, modelNames):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(modelNames), 0)

def AddModelNames(builder, modelNames):
    DebugPrimitivesAddModelNames(builder, modelNames)

def DebugPrimitivesStartModelNamesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartModelNamesVector(builder, numElems):
    return DebugPrimitivesStartModelNamesVector(builder, numElems)

def DebugPrimitivesAddModelOffsets(builder, modelOffsets):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(modelOffsets), 0)

def AddModelOffsets(builder, modelOffsets):
    DebugPrimitivesAddModelOffsets(builder, modelOffsets)

def DebugPrimitivesStartModelOffsetsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartModelOffsetsVector(builder, numElems):
    return DebugPrimitivesStartModelOffsetsVector(builder, numElems)

def DebugPrimitivesAddVertices(builder, vertices):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(vertices), 0)

def AddVertices(builder, vertices):
    DebugPrimitivesAddVertices(builder, vertices)

def DebugPrimitivesStartVerticesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartVerticesVector(builder, numElems):
    return DebugPrimitivesStartVerticesVector(builder, numElems)

def DebugPrimitivesAddIndices(builder, indices):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(indices), 0)

def AddIndices(builder, indices):
    DebugPrimitivesAddIndices(builder, indices)

def DebugPrimitivesStartIndicesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartIndicesVector(builder, numElems):
    return DebugPrimitivesStartIndicesVector(builder, numElems)

def DebugPrimitivesEnd(builder):
    return builder.EndObject()

def End(builder):
    return DebugPrimitivesEnd(builder)
