# automatically generated by the FlatBuffers compiler, do not modify

# namespace: debug

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DebugPrimitiveVertex(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DebugPrimitiveVertex()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDebugPrimitiveVertex(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DebugPrimitiveVertex
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DebugPrimitiveVertex
    def Position(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # DebugPrimitiveVertex
    def PositionAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # DebugPrimitiveVertex
    def PositionLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DebugPrimitiveVertex
    def PositionIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # DebugPrimitiveVertex
    def Normal(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # DebugPrimitiveVertex
    def NormalAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # DebugPrimitiveVertex
    def NormalLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DebugPrimitiveVertex
    def NormalIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def DebugPrimitiveVertexStart(builder):
    builder.StartObject(2)

def Start(builder):
    DebugPrimitiveVertexStart(builder)

def DebugPrimitiveVertexAddPosition(builder, position):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(position), 0)

def AddPosition(builder, position):
    DebugPrimitiveVertexAddPosition(builder, position)

def DebugPrimitiveVertexStartPositionVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartPositionVector(builder, numElems):
    return DebugPrimitiveVertexStartPositionVector(builder, numElems)

def DebugPrimitiveVertexAddNormal(builder, normal):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(normal), 0)

def AddNormal(builder, normal):
    DebugPrimitiveVertexAddNormal(builder, normal)

def DebugPrimitiveVertexStartNormalVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartNormalVector(builder, numElems):
    return DebugPrimitiveVertexStartNormalVector(builder, numElems)

def DebugPrimitiveVertexEnd(builder):
    return builder.EndObject()

def End(builder):
    return DebugPrimitiveVertexEnd(builder)
