# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gl

class ShaderStage(object):
    Vertex = 0
    Fragment = 1
    Compute = 2
    Geometry = 3
    TessControl = 4
    TessEval = 5
