# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ShaderFile(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ShaderFile()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsShaderFile(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ShaderFile
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ShaderFile
    def Shaders(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from gl.ShaderEntry import ShaderEntry
            obj = ShaderEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ShaderFile
    def ShadersLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ShaderFile
    def ShadersIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ShaderFileStart(builder):
    builder.StartObject(1)

def Start(builder):
    ShaderFileStart(builder)

def ShaderFileAddShaders(builder, shaders):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(shaders), 0)

def AddShaders(builder, shaders):
    ShaderFileAddShaders(builder, shaders)

def ShaderFileStartShadersVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartShadersVector(builder, numElems):
    return ShaderFileStartShadersVector(builder, numElems)

def ShaderFileEnd(builder):
    return builder.EndObject()

def End(builder):
    return ShaderFileEnd(builder)
