# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gl

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ShaderEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ShaderEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsShaderEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ShaderEntry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ShaderEntry
    def Stage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # ShaderEntry
    def Source(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ShaderEntryStart(builder):
    builder.StartObject(2)

def Start(builder):
    ShaderEntryStart(builder)

def ShaderEntryAddStage(builder, stage):
    builder.PrependInt8Slot(0, stage, 0)

def AddStage(builder, stage):
    ShaderEntryAddStage(builder, stage)

def ShaderEntryAddSource(builder, source):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(source), 0)

def AddSource(builder, source):
    ShaderEntryAddSource(builder, source)

def ShaderEntryEnd(builder):
    return builder.EndObject()

def End(builder):
    return ShaderEntryEnd(builder)
