# automatically generated by the FlatBuffers compiler, do not modify

# namespace: pbr

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TexturePool(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TexturePool()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTexturePool(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TexturePool
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TexturePool
    def PoolType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # TexturePool
    def Width(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # TexturePool
    def Height(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # TexturePool
    def Channels(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # TexturePool
    def ImagePaths(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # TexturePool
    def ImagePathsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TexturePool
    def ImagePathsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

def TexturePoolStart(builder):
    builder.StartObject(5)

def Start(builder):
    TexturePoolStart(builder)

def TexturePoolAddPoolType(builder, poolType):
    builder.PrependInt8Slot(0, poolType, 0)

def AddPoolType(builder, poolType):
    TexturePoolAddPoolType(builder, poolType)

def TexturePoolAddWidth(builder, width):
    builder.PrependUint32Slot(1, width, 0)

def AddWidth(builder, width):
    TexturePoolAddWidth(builder, width)

def TexturePoolAddHeight(builder, height):
    builder.PrependUint32Slot(2, height, 0)

def AddHeight(builder, height):
    TexturePoolAddHeight(builder, height)

def TexturePoolAddChannels(builder, channels):
    builder.PrependUint32Slot(3, channels, 0)

def AddChannels(builder, channels):
    TexturePoolAddChannels(builder, channels)

def TexturePoolAddImagePaths(builder, imagePaths):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(imagePaths), 0)

def AddImagePaths(builder, imagePaths):
    TexturePoolAddImagePaths(builder, imagePaths)

def TexturePoolStartImagePathsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartImagePathsVector(builder, numElems):
    return TexturePoolStartImagePathsVector(builder, numElems)

def TexturePoolEnd(builder):
    return builder.EndObject()

def End(builder):
    return TexturePoolEnd(builder)
