# automatically generated by the FlatBuffers compiler, do not modify

# namespace: pbr

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TexturePoolList(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TexturePoolList()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTexturePoolList(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TexturePoolList
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TexturePoolList
    def Pools(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from gl.pbr.TexturePool import TexturePool
            obj = TexturePool()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TexturePoolList
    def PoolsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TexturePoolList
    def PoolsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # TexturePoolList
    def Defaults(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # TexturePoolList
    def DefaultsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TexturePoolList
    def DefaultsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def TexturePoolListStart(builder):
    builder.StartObject(2)

def Start(builder):
    TexturePoolListStart(builder)

def TexturePoolListAddPools(builder, pools):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(pools), 0)

def AddPools(builder, pools):
    TexturePoolListAddPools(builder, pools)

def TexturePoolListStartPoolsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartPoolsVector(builder, numElems):
    return TexturePoolListStartPoolsVector(builder, numElems)

def TexturePoolListAddDefaults(builder, defaults):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(defaults), 0)

def AddDefaults(builder, defaults):
    TexturePoolListAddDefaults(builder, defaults)

def TexturePoolListStartDefaultsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDefaultsVector(builder, numElems):
    return TexturePoolListStartDefaultsVector(builder, numElems)

def TexturePoolListEnd(builder):
    return builder.EndObject()

def End(builder):
    return TexturePoolListEnd(builder)
