// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SHADER_GL_H_
#define FLATBUFFERS_GENERATED_SHADER_GL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace gl {

struct ShaderEntry;
struct ShaderEntryBuilder;

struct ShaderFile;
struct ShaderFileBuilder;

enum ShaderStage : int8_t {
  ShaderStage_Vertex = 0,
  ShaderStage_Fragment = 1,
  ShaderStage_Compute = 2,
  ShaderStage_Geometry = 3,
  ShaderStage_TessControl = 4,
  ShaderStage_TessEval = 5,
  ShaderStage_MIN = ShaderStage_Vertex,
  ShaderStage_MAX = ShaderStage_TessEval
};

inline const ShaderStage (&EnumValuesShaderStage())[6] {
  static const ShaderStage values[] = {
    ShaderStage_Vertex,
    ShaderStage_Fragment,
    ShaderStage_Compute,
    ShaderStage_Geometry,
    ShaderStage_TessControl,
    ShaderStage_TessEval
  };
  return values;
}

inline const char * const *EnumNamesShaderStage() {
  static const char * const names[7] = {
    "Vertex",
    "Fragment",
    "Compute",
    "Geometry",
    "TessControl",
    "TessEval",
    nullptr
  };
  return names;
}

inline const char *EnumNameShaderStage(ShaderStage e) {
  if (::flatbuffers::IsOutRange(e, ShaderStage_Vertex, ShaderStage_TessEval)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesShaderStage()[index];
}

struct ShaderEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ShaderEntryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_STAGE = 4,
    VT_SOURCE = 6
  };
  gl::ShaderStage stage() const {
    return static_cast<gl::ShaderStage>(GetField<int8_t>(VT_STAGE, 0));
  }
  const ::flatbuffers::String *source() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SOURCE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_STAGE, 1) &&
           VerifyOffset(verifier, VT_SOURCE) &&
           verifier.VerifyString(source()) &&
           verifier.EndTable();
  }
};

struct ShaderEntryBuilder {
  typedef ShaderEntry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_stage(gl::ShaderStage stage) {
    fbb_.AddElement<int8_t>(ShaderEntry::VT_STAGE, static_cast<int8_t>(stage), 0);
  }
  void add_source(::flatbuffers::Offset<::flatbuffers::String> source) {
    fbb_.AddOffset(ShaderEntry::VT_SOURCE, source);
  }
  explicit ShaderEntryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ShaderEntry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ShaderEntry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ShaderEntry> CreateShaderEntry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    gl::ShaderStage stage = gl::ShaderStage_Vertex,
    ::flatbuffers::Offset<::flatbuffers::String> source = 0) {
  ShaderEntryBuilder builder_(_fbb);
  builder_.add_source(source);
  builder_.add_stage(stage);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ShaderEntry> CreateShaderEntryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    gl::ShaderStage stage = gl::ShaderStage_Vertex,
    const char *source = nullptr) {
  auto source__ = source ? _fbb.CreateString(source) : 0;
  return gl::CreateShaderEntry(
      _fbb,
      stage,
      source__);
}

struct ShaderFile FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ShaderFileBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SHADERS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<gl::ShaderEntry>> *shaders() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<gl::ShaderEntry>> *>(VT_SHADERS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SHADERS) &&
           verifier.VerifyVector(shaders()) &&
           verifier.VerifyVectorOfTables(shaders()) &&
           verifier.EndTable();
  }
};

struct ShaderFileBuilder {
  typedef ShaderFile Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_shaders(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<gl::ShaderEntry>>> shaders) {
    fbb_.AddOffset(ShaderFile::VT_SHADERS, shaders);
  }
  explicit ShaderFileBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ShaderFile> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ShaderFile>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ShaderFile> CreateShaderFile(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<gl::ShaderEntry>>> shaders = 0) {
  ShaderFileBuilder builder_(_fbb);
  builder_.add_shaders(shaders);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ShaderFile> CreateShaderFileDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<gl::ShaderEntry>> *shaders = nullptr) {
  auto shaders__ = shaders ? _fbb.CreateVector<::flatbuffers::Offset<gl::ShaderEntry>>(*shaders) : 0;
  return gl::CreateShaderFile(
      _fbb,
      shaders__);
}

inline const gl::ShaderFile *GetShaderFile(const void *buf) {
  return ::flatbuffers::GetRoot<gl::ShaderFile>(buf);
}

inline const gl::ShaderFile *GetSizePrefixedShaderFile(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<gl::ShaderFile>(buf);
}

inline bool VerifyShaderFileBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<gl::ShaderFile>(nullptr);
}

inline bool VerifySizePrefixedShaderFileBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<gl::ShaderFile>(nullptr);
}

inline void FinishShaderFileBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<gl::ShaderFile> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedShaderFileBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<gl::ShaderFile> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace gl

#endif  // FLATBUFFERS_GENERATED_SHADER_GL_H_
