// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TEXTUREPOOL_GL_PBR_H_
#define FLATBUFFERS_GENERATED_TEXTUREPOOL_GL_PBR_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace gl {
namespace pbr {

struct TexturePool;
struct TexturePoolBuilder;

struct TexturePoolList;
struct TexturePoolListBuilder;

enum TexturePoolType : int8_t {
  TexturePoolType_Albedo = 0,
  TexturePoolType_MRAO = 1,
  TexturePoolType_Normal = 2,
  TexturePoolType_Emissive = 3,
  TexturePoolType_MIN = TexturePoolType_Albedo,
  TexturePoolType_MAX = TexturePoolType_Emissive
};

inline const TexturePoolType (&EnumValuesTexturePoolType())[4] {
  static const TexturePoolType values[] = {
    TexturePoolType_Albedo,
    TexturePoolType_MRAO,
    TexturePoolType_Normal,
    TexturePoolType_Emissive
  };
  return values;
}

inline const char * const *EnumNamesTexturePoolType() {
  static const char * const names[5] = {
    "Albedo",
    "MRAO",
    "Normal",
    "Emissive",
    nullptr
  };
  return names;
}

inline const char *EnumNameTexturePoolType(TexturePoolType e) {
  if (::flatbuffers::IsOutRange(e, TexturePoolType_Albedo, TexturePoolType_Emissive)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTexturePoolType()[index];
}

struct TexturePool FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TexturePoolBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POOL_TYPE = 4,
    VT_WIDTH = 6,
    VT_HEIGHT = 8,
    VT_CHANNELS = 10,
    VT_IMAGE_PATHS = 12
  };
  gl::pbr::TexturePoolType pool_type() const {
    return static_cast<gl::pbr::TexturePoolType>(GetField<int8_t>(VT_POOL_TYPE, 0));
  }
  uint32_t width() const {
    return GetField<uint32_t>(VT_WIDTH, 0);
  }
  uint32_t height() const {
    return GetField<uint32_t>(VT_HEIGHT, 0);
  }
  uint32_t channels() const {
    return GetField<uint32_t>(VT_CHANNELS, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *image_paths() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_IMAGE_PATHS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_POOL_TYPE, 1) &&
           VerifyField<uint32_t>(verifier, VT_WIDTH, 4) &&
           VerifyField<uint32_t>(verifier, VT_HEIGHT, 4) &&
           VerifyField<uint32_t>(verifier, VT_CHANNELS, 4) &&
           VerifyOffset(verifier, VT_IMAGE_PATHS) &&
           verifier.VerifyVector(image_paths()) &&
           verifier.VerifyVectorOfStrings(image_paths()) &&
           verifier.EndTable();
  }
};

struct TexturePoolBuilder {
  typedef TexturePool Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_pool_type(gl::pbr::TexturePoolType pool_type) {
    fbb_.AddElement<int8_t>(TexturePool::VT_POOL_TYPE, static_cast<int8_t>(pool_type), 0);
  }
  void add_width(uint32_t width) {
    fbb_.AddElement<uint32_t>(TexturePool::VT_WIDTH, width, 0);
  }
  void add_height(uint32_t height) {
    fbb_.AddElement<uint32_t>(TexturePool::VT_HEIGHT, height, 0);
  }
  void add_channels(uint32_t channels) {
    fbb_.AddElement<uint32_t>(TexturePool::VT_CHANNELS, channels, 0);
  }
  void add_image_paths(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> image_paths) {
    fbb_.AddOffset(TexturePool::VT_IMAGE_PATHS, image_paths);
  }
  explicit TexturePoolBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TexturePool> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TexturePool>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TexturePool> CreateTexturePool(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    gl::pbr::TexturePoolType pool_type = gl::pbr::TexturePoolType_Albedo,
    uint32_t width = 0,
    uint32_t height = 0,
    uint32_t channels = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> image_paths = 0) {
  TexturePoolBuilder builder_(_fbb);
  builder_.add_image_paths(image_paths);
  builder_.add_channels(channels);
  builder_.add_height(height);
  builder_.add_width(width);
  builder_.add_pool_type(pool_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TexturePool> CreateTexturePoolDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    gl::pbr::TexturePoolType pool_type = gl::pbr::TexturePoolType_Albedo,
    uint32_t width = 0,
    uint32_t height = 0,
    uint32_t channels = 0,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *image_paths = nullptr) {
  auto image_paths__ = image_paths ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*image_paths) : 0;
  return gl::pbr::CreateTexturePool(
      _fbb,
      pool_type,
      width,
      height,
      channels,
      image_paths__);
}

struct TexturePoolList FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TexturePoolListBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POOLS = 4,
    VT_DEFAULTS = 6
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<gl::pbr::TexturePool>> *pools() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<gl::pbr::TexturePool>> *>(VT_POOLS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *defaults() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_DEFAULTS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_POOLS) &&
           verifier.VerifyVector(pools()) &&
           verifier.VerifyVectorOfTables(pools()) &&
           VerifyOffset(verifier, VT_DEFAULTS) &&
           verifier.VerifyVector(defaults()) &&
           verifier.VerifyVectorOfStrings(defaults()) &&
           verifier.EndTable();
  }
};

struct TexturePoolListBuilder {
  typedef TexturePoolList Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_pools(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<gl::pbr::TexturePool>>> pools) {
    fbb_.AddOffset(TexturePoolList::VT_POOLS, pools);
  }
  void add_defaults(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> defaults) {
    fbb_.AddOffset(TexturePoolList::VT_DEFAULTS, defaults);
  }
  explicit TexturePoolListBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TexturePoolList> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TexturePoolList>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TexturePoolList> CreateTexturePoolList(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<gl::pbr::TexturePool>>> pools = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> defaults = 0) {
  TexturePoolListBuilder builder_(_fbb);
  builder_.add_defaults(defaults);
  builder_.add_pools(pools);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TexturePoolList> CreateTexturePoolListDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<gl::pbr::TexturePool>> *pools = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *defaults = nullptr) {
  auto pools__ = pools ? _fbb.CreateVector<::flatbuffers::Offset<gl::pbr::TexturePool>>(*pools) : 0;
  auto defaults__ = defaults ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*defaults) : 0;
  return gl::pbr::CreateTexturePoolList(
      _fbb,
      pools__,
      defaults__);
}

inline const gl::pbr::TexturePoolList *GetTexturePoolList(const void *buf) {
  return ::flatbuffers::GetRoot<gl::pbr::TexturePoolList>(buf);
}

inline const gl::pbr::TexturePoolList *GetSizePrefixedTexturePoolList(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<gl::pbr::TexturePoolList>(buf);
}

inline bool VerifyTexturePoolListBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<gl::pbr::TexturePoolList>(nullptr);
}

inline bool VerifySizePrefixedTexturePoolListBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<gl::pbr::TexturePoolList>(nullptr);
}

inline void FinishTexturePoolListBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<gl::pbr::TexturePoolList> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedTexturePoolListBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<gl::pbr::TexturePoolList> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace pbr
}  // namespace gl

#endif  // FLATBUFFERS_GENERATED_TEXTUREPOOL_GL_PBR_H_
