// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: debug_primitives.proto

#include "debug_primitives.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace gl {
namespace debug {
PROTOBUF_CONSTEXPR DebugPrimitiveModel::DebugPrimitiveModel(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.vert_offset_)*/0u
  , /*decltype(_impl_.ebo_offset_)*/0u
  , /*decltype(_impl_.vert_length_)*/0u
  , /*decltype(_impl_.ebo_length_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DebugPrimitiveModelDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DebugPrimitiveModelDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DebugPrimitiveModelDefaultTypeInternal() {}
  union {
    DebugPrimitiveModel _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DebugPrimitiveModelDefaultTypeInternal _DebugPrimitiveModel_default_instance_;
PROTOBUF_CONSTEXPR DebugPrimitiveVertex::DebugPrimitiveVertex(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.position_)*/{}
  , /*decltype(_impl_.normal_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DebugPrimitiveVertexDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DebugPrimitiveVertexDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DebugPrimitiveVertexDefaultTypeInternal() {}
  union {
    DebugPrimitiveVertex _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DebugPrimitiveVertexDefaultTypeInternal _DebugPrimitiveVertex_default_instance_;
PROTOBUF_CONSTEXPR DebugPrimitives::DebugPrimitives(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.model_names_)*/{}
  , /*decltype(_impl_.model_offsets_)*/{}
  , /*decltype(_impl_.vertices_)*/{}
  , /*decltype(_impl_.indices_)*/{}
  , /*decltype(_impl_._indices_cached_byte_size_)*/{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DebugPrimitivesDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DebugPrimitivesDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DebugPrimitivesDefaultTypeInternal() {}
  union {
    DebugPrimitives _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DebugPrimitivesDefaultTypeInternal _DebugPrimitives_default_instance_;
}  // namespace debug
}  // namespace gl
static ::_pb::Metadata file_level_metadata_debug_5fprimitives_2eproto[3];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_debug_5fprimitives_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_debug_5fprimitives_2eproto = nullptr;

const uint32_t TableStruct_debug_5fprimitives_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::gl::debug::DebugPrimitiveModel, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::gl::debug::DebugPrimitiveModel, _impl_.vert_offset_),
  PROTOBUF_FIELD_OFFSET(::gl::debug::DebugPrimitiveModel, _impl_.ebo_offset_),
  PROTOBUF_FIELD_OFFSET(::gl::debug::DebugPrimitiveModel, _impl_.vert_length_),
  PROTOBUF_FIELD_OFFSET(::gl::debug::DebugPrimitiveModel, _impl_.ebo_length_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::gl::debug::DebugPrimitiveVertex, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::gl::debug::DebugPrimitiveVertex, _impl_.position_),
  PROTOBUF_FIELD_OFFSET(::gl::debug::DebugPrimitiveVertex, _impl_.normal_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::gl::debug::DebugPrimitives, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::gl::debug::DebugPrimitives, _impl_.model_names_),
  PROTOBUF_FIELD_OFFSET(::gl::debug::DebugPrimitives, _impl_.model_offsets_),
  PROTOBUF_FIELD_OFFSET(::gl::debug::DebugPrimitives, _impl_.vertices_),
  PROTOBUF_FIELD_OFFSET(::gl::debug::DebugPrimitives, _impl_.indices_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::gl::debug::DebugPrimitiveModel)},
  { 10, -1, -1, sizeof(::gl::debug::DebugPrimitiveVertex)},
  { 18, -1, -1, sizeof(::gl::debug::DebugPrimitives)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::gl::debug::_DebugPrimitiveModel_default_instance_._instance,
  &::gl::debug::_DebugPrimitiveVertex_default_instance_._instance,
  &::gl::debug::_DebugPrimitives_default_instance_._instance,
};

const char descriptor_table_protodef_debug_5fprimitives_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\026debug_primitives.proto\022\010gl.debug\"g\n\023De"
  "bugPrimitiveModel\022\023\n\013vert_offset\030\001 \001(\r\022\022"
  "\n\nebo_offset\030\002 \001(\r\022\023\n\013vert_length\030\003 \001(\r\022"
  "\022\n\nebo_length\030\004 \001(\r\"8\n\024DebugPrimitiveVer"
  "tex\022\020\n\010position\030\001 \003(\002\022\016\n\006normal\030\002 \003(\002\"\237\001"
  "\n\017DebugPrimitives\022\023\n\013model_names\030\001 \003(\t\0224"
  "\n\rmodel_offsets\030\002 \003(\0132\035.gl.debug.DebugPr"
  "imitiveModel\0220\n\010vertices\030\003 \003(\0132\036.gl.debu"
  "g.DebugPrimitiveVertex\022\017\n\007indices\030\004 \003(\rb"
  "\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_debug_5fprimitives_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_debug_5fprimitives_2eproto = {
    false, false, 367, descriptor_table_protodef_debug_5fprimitives_2eproto,
    "debug_primitives.proto",
    &descriptor_table_debug_5fprimitives_2eproto_once, nullptr, 0, 3,
    schemas, file_default_instances, TableStruct_debug_5fprimitives_2eproto::offsets,
    file_level_metadata_debug_5fprimitives_2eproto, file_level_enum_descriptors_debug_5fprimitives_2eproto,
    file_level_service_descriptors_debug_5fprimitives_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_debug_5fprimitives_2eproto_getter() {
  return &descriptor_table_debug_5fprimitives_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_debug_5fprimitives_2eproto(&descriptor_table_debug_5fprimitives_2eproto);
namespace gl {
namespace debug {

// ===================================================================

class DebugPrimitiveModel::_Internal {
 public:
};

DebugPrimitiveModel::DebugPrimitiveModel(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:gl.debug.DebugPrimitiveModel)
}
DebugPrimitiveModel::DebugPrimitiveModel(const DebugPrimitiveModel& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DebugPrimitiveModel* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.vert_offset_){}
    , decltype(_impl_.ebo_offset_){}
    , decltype(_impl_.vert_length_){}
    , decltype(_impl_.ebo_length_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.vert_offset_, &from._impl_.vert_offset_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.ebo_length_) -
    reinterpret_cast<char*>(&_impl_.vert_offset_)) + sizeof(_impl_.ebo_length_));
  // @@protoc_insertion_point(copy_constructor:gl.debug.DebugPrimitiveModel)
}

inline void DebugPrimitiveModel::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.vert_offset_){0u}
    , decltype(_impl_.ebo_offset_){0u}
    , decltype(_impl_.vert_length_){0u}
    , decltype(_impl_.ebo_length_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

DebugPrimitiveModel::~DebugPrimitiveModel() {
  // @@protoc_insertion_point(destructor:gl.debug.DebugPrimitiveModel)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DebugPrimitiveModel::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void DebugPrimitiveModel::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DebugPrimitiveModel::Clear() {
// @@protoc_insertion_point(message_clear_start:gl.debug.DebugPrimitiveModel)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.vert_offset_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.ebo_length_) -
      reinterpret_cast<char*>(&_impl_.vert_offset_)) + sizeof(_impl_.ebo_length_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DebugPrimitiveModel::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 vert_offset = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.vert_offset_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 ebo_offset = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.ebo_offset_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 vert_length = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.vert_length_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 ebo_length = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.ebo_length_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DebugPrimitiveModel::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:gl.debug.DebugPrimitiveModel)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 vert_offset = 1;
  if (this->_internal_vert_offset() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_vert_offset(), target);
  }

  // uint32 ebo_offset = 2;
  if (this->_internal_ebo_offset() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_ebo_offset(), target);
  }

  // uint32 vert_length = 3;
  if (this->_internal_vert_length() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_vert_length(), target);
  }

  // uint32 ebo_length = 4;
  if (this->_internal_ebo_length() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_ebo_length(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gl.debug.DebugPrimitiveModel)
  return target;
}

size_t DebugPrimitiveModel::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gl.debug.DebugPrimitiveModel)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 vert_offset = 1;
  if (this->_internal_vert_offset() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_vert_offset());
  }

  // uint32 ebo_offset = 2;
  if (this->_internal_ebo_offset() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_ebo_offset());
  }

  // uint32 vert_length = 3;
  if (this->_internal_vert_length() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_vert_length());
  }

  // uint32 ebo_length = 4;
  if (this->_internal_ebo_length() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_ebo_length());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DebugPrimitiveModel::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DebugPrimitiveModel::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DebugPrimitiveModel::GetClassData() const { return &_class_data_; }


void DebugPrimitiveModel::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DebugPrimitiveModel*>(&to_msg);
  auto& from = static_cast<const DebugPrimitiveModel&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gl.debug.DebugPrimitiveModel)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_vert_offset() != 0) {
    _this->_internal_set_vert_offset(from._internal_vert_offset());
  }
  if (from._internal_ebo_offset() != 0) {
    _this->_internal_set_ebo_offset(from._internal_ebo_offset());
  }
  if (from._internal_vert_length() != 0) {
    _this->_internal_set_vert_length(from._internal_vert_length());
  }
  if (from._internal_ebo_length() != 0) {
    _this->_internal_set_ebo_length(from._internal_ebo_length());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DebugPrimitiveModel::CopyFrom(const DebugPrimitiveModel& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gl.debug.DebugPrimitiveModel)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DebugPrimitiveModel::IsInitialized() const {
  return true;
}

void DebugPrimitiveModel::InternalSwap(DebugPrimitiveModel* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DebugPrimitiveModel, _impl_.ebo_length_)
      + sizeof(DebugPrimitiveModel::_impl_.ebo_length_)
      - PROTOBUF_FIELD_OFFSET(DebugPrimitiveModel, _impl_.vert_offset_)>(
          reinterpret_cast<char*>(&_impl_.vert_offset_),
          reinterpret_cast<char*>(&other->_impl_.vert_offset_));
}

::PROTOBUF_NAMESPACE_ID::Metadata DebugPrimitiveModel::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_debug_5fprimitives_2eproto_getter, &descriptor_table_debug_5fprimitives_2eproto_once,
      file_level_metadata_debug_5fprimitives_2eproto[0]);
}

// ===================================================================

class DebugPrimitiveVertex::_Internal {
 public:
};

DebugPrimitiveVertex::DebugPrimitiveVertex(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:gl.debug.DebugPrimitiveVertex)
}
DebugPrimitiveVertex::DebugPrimitiveVertex(const DebugPrimitiveVertex& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DebugPrimitiveVertex* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.position_){from._impl_.position_}
    , decltype(_impl_.normal_){from._impl_.normal_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:gl.debug.DebugPrimitiveVertex)
}

inline void DebugPrimitiveVertex::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.position_){arena}
    , decltype(_impl_.normal_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

DebugPrimitiveVertex::~DebugPrimitiveVertex() {
  // @@protoc_insertion_point(destructor:gl.debug.DebugPrimitiveVertex)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DebugPrimitiveVertex::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.position_.~RepeatedField();
  _impl_.normal_.~RepeatedField();
}

void DebugPrimitiveVertex::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DebugPrimitiveVertex::Clear() {
// @@protoc_insertion_point(message_clear_start:gl.debug.DebugPrimitiveVertex)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.position_.Clear();
  _impl_.normal_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DebugPrimitiveVertex::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated float position = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_position(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 13) {
          _internal_add_position(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // repeated float normal = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_normal(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 21) {
          _internal_add_normal(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DebugPrimitiveVertex::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:gl.debug.DebugPrimitiveVertex)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float position = 1;
  if (this->_internal_position_size() > 0) {
    target = stream->WriteFixedPacked(1, _internal_position(), target);
  }

  // repeated float normal = 2;
  if (this->_internal_normal_size() > 0) {
    target = stream->WriteFixedPacked(2, _internal_normal(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gl.debug.DebugPrimitiveVertex)
  return target;
}

size_t DebugPrimitiveVertex::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gl.debug.DebugPrimitiveVertex)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float position = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_position_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // repeated float normal = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_normal_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DebugPrimitiveVertex::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DebugPrimitiveVertex::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DebugPrimitiveVertex::GetClassData() const { return &_class_data_; }


void DebugPrimitiveVertex::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DebugPrimitiveVertex*>(&to_msg);
  auto& from = static_cast<const DebugPrimitiveVertex&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gl.debug.DebugPrimitiveVertex)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.position_.MergeFrom(from._impl_.position_);
  _this->_impl_.normal_.MergeFrom(from._impl_.normal_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DebugPrimitiveVertex::CopyFrom(const DebugPrimitiveVertex& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gl.debug.DebugPrimitiveVertex)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DebugPrimitiveVertex::IsInitialized() const {
  return true;
}

void DebugPrimitiveVertex::InternalSwap(DebugPrimitiveVertex* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.position_.InternalSwap(&other->_impl_.position_);
  _impl_.normal_.InternalSwap(&other->_impl_.normal_);
}

::PROTOBUF_NAMESPACE_ID::Metadata DebugPrimitiveVertex::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_debug_5fprimitives_2eproto_getter, &descriptor_table_debug_5fprimitives_2eproto_once,
      file_level_metadata_debug_5fprimitives_2eproto[1]);
}

// ===================================================================

class DebugPrimitives::_Internal {
 public:
};

DebugPrimitives::DebugPrimitives(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:gl.debug.DebugPrimitives)
}
DebugPrimitives::DebugPrimitives(const DebugPrimitives& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DebugPrimitives* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.model_names_){from._impl_.model_names_}
    , decltype(_impl_.model_offsets_){from._impl_.model_offsets_}
    , decltype(_impl_.vertices_){from._impl_.vertices_}
    , decltype(_impl_.indices_){from._impl_.indices_}
    , /*decltype(_impl_._indices_cached_byte_size_)*/{0}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:gl.debug.DebugPrimitives)
}

inline void DebugPrimitives::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.model_names_){arena}
    , decltype(_impl_.model_offsets_){arena}
    , decltype(_impl_.vertices_){arena}
    , decltype(_impl_.indices_){arena}
    , /*decltype(_impl_._indices_cached_byte_size_)*/{0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

DebugPrimitives::~DebugPrimitives() {
  // @@protoc_insertion_point(destructor:gl.debug.DebugPrimitives)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DebugPrimitives::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.model_names_.~RepeatedPtrField();
  _impl_.model_offsets_.~RepeatedPtrField();
  _impl_.vertices_.~RepeatedPtrField();
  _impl_.indices_.~RepeatedField();
}

void DebugPrimitives::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DebugPrimitives::Clear() {
// @@protoc_insertion_point(message_clear_start:gl.debug.DebugPrimitives)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.model_names_.Clear();
  _impl_.model_offsets_.Clear();
  _impl_.vertices_.Clear();
  _impl_.indices_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DebugPrimitives::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated string model_names = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_model_names();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "gl.debug.DebugPrimitives.model_names"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .gl.debug.DebugPrimitiveModel model_offsets = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_model_offsets(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .gl.debug.DebugPrimitiveVertex vertices = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_vertices(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated uint32 indices = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedUInt32Parser(_internal_mutable_indices(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 32) {
          _internal_add_indices(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DebugPrimitives::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:gl.debug.DebugPrimitives)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string model_names = 1;
  for (int i = 0, n = this->_internal_model_names_size(); i < n; i++) {
    const auto& s = this->_internal_model_names(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "gl.debug.DebugPrimitives.model_names");
    target = stream->WriteString(1, s, target);
  }

  // repeated .gl.debug.DebugPrimitiveModel model_offsets = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_model_offsets_size()); i < n; i++) {
    const auto& repfield = this->_internal_model_offsets(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .gl.debug.DebugPrimitiveVertex vertices = 3;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_vertices_size()); i < n; i++) {
    const auto& repfield = this->_internal_vertices(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(3, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated uint32 indices = 4;
  {
    int byte_size = _impl_._indices_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteUInt32Packed(
          4, _internal_indices(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gl.debug.DebugPrimitives)
  return target;
}

size_t DebugPrimitives::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gl.debug.DebugPrimitives)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string model_names = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.model_names_.size());
  for (int i = 0, n = _impl_.model_names_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.model_names_.Get(i));
  }

  // repeated .gl.debug.DebugPrimitiveModel model_offsets = 2;
  total_size += 1UL * this->_internal_model_offsets_size();
  for (const auto& msg : this->_impl_.model_offsets_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .gl.debug.DebugPrimitiveVertex vertices = 3;
  total_size += 1UL * this->_internal_vertices_size();
  for (const auto& msg : this->_impl_.vertices_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated uint32 indices = 4;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      UInt32Size(this->_impl_.indices_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._indices_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DebugPrimitives::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DebugPrimitives::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DebugPrimitives::GetClassData() const { return &_class_data_; }


void DebugPrimitives::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DebugPrimitives*>(&to_msg);
  auto& from = static_cast<const DebugPrimitives&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gl.debug.DebugPrimitives)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.model_names_.MergeFrom(from._impl_.model_names_);
  _this->_impl_.model_offsets_.MergeFrom(from._impl_.model_offsets_);
  _this->_impl_.vertices_.MergeFrom(from._impl_.vertices_);
  _this->_impl_.indices_.MergeFrom(from._impl_.indices_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DebugPrimitives::CopyFrom(const DebugPrimitives& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gl.debug.DebugPrimitives)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DebugPrimitives::IsInitialized() const {
  return true;
}

void DebugPrimitives::InternalSwap(DebugPrimitives* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.model_names_.InternalSwap(&other->_impl_.model_names_);
  _impl_.model_offsets_.InternalSwap(&other->_impl_.model_offsets_);
  _impl_.vertices_.InternalSwap(&other->_impl_.vertices_);
  _impl_.indices_.InternalSwap(&other->_impl_.indices_);
}

::PROTOBUF_NAMESPACE_ID::Metadata DebugPrimitives::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_debug_5fprimitives_2eproto_getter, &descriptor_table_debug_5fprimitives_2eproto_once,
      file_level_metadata_debug_5fprimitives_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace debug
}  // namespace gl
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::gl::debug::DebugPrimitiveModel*
Arena::CreateMaybeMessage< ::gl::debug::DebugPrimitiveModel >(Arena* arena) {
  return Arena::CreateMessageInternal< ::gl::debug::DebugPrimitiveModel >(arena);
}
template<> PROTOBUF_NOINLINE ::gl::debug::DebugPrimitiveVertex*
Arena::CreateMaybeMessage< ::gl::debug::DebugPrimitiveVertex >(Arena* arena) {
  return Arena::CreateMessageInternal< ::gl::debug::DebugPrimitiveVertex >(arena);
}
template<> PROTOBUF_NOINLINE ::gl::debug::DebugPrimitives*
Arena::CreateMaybeMessage< ::gl::debug::DebugPrimitives >(Arena* arena) {
  return Arena::CreateMessageInternal< ::gl::debug::DebugPrimitives >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
