// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbr_meta.proto

#include "pbr_meta.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace gl {
namespace pbr {
namespace data {
PROTOBUF_CONSTEXPR TexturePool::TexturePool(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.type_)*/0
  , /*decltype(_impl_.depth_)*/0u
  , /*decltype(_impl_.width_)*/0u
  , /*decltype(_impl_.height_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TexturePoolDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TexturePoolDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TexturePoolDefaultTypeInternal() {}
  union {
    TexturePool _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TexturePoolDefaultTypeInternal _TexturePool_default_instance_;
PROTOBUF_CONSTEXPR PBRCache::PBRCache(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.texture_pools_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PBRCacheDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PBRCacheDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PBRCacheDefaultTypeInternal() {}
  union {
    PBRCache _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PBRCacheDefaultTypeInternal _PBRCache_default_instance_;
}  // namespace data
}  // namespace pbr
}  // namespace gl
static ::_pb::Metadata file_level_metadata_pbr_5fmeta_2eproto[2];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_pbr_5fmeta_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_pbr_5fmeta_2eproto = nullptr;

const uint32_t TableStruct_pbr_5fmeta_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::gl::pbr::data::TexturePool, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::gl::pbr::data::TexturePool, _impl_.type_),
  PROTOBUF_FIELD_OFFSET(::gl::pbr::data::TexturePool, _impl_.depth_),
  PROTOBUF_FIELD_OFFSET(::gl::pbr::data::TexturePool, _impl_.width_),
  PROTOBUF_FIELD_OFFSET(::gl::pbr::data::TexturePool, _impl_.height_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::gl::pbr::data::PBRCache, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::gl::pbr::data::PBRCache, _impl_.texture_pools_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::gl::pbr::data::TexturePool)},
  { 10, -1, -1, sizeof(::gl::pbr::data::PBRCache)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::gl::pbr::data::_TexturePool_default_instance_._instance,
  &::gl::pbr::data::_PBRCache_default_instance_._instance,
};

const char descriptor_table_protodef_pbr_5fmeta_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016pbr_meta.proto\022\013gl.pbr.data\"c\n\013Texture"
  "Pool\022&\n\004type\030\001 \001(\0162\030.gl.pbr.data.Texture"
  "Type\022\r\n\005depth\030\002 \001(\r\022\r\n\005width\030\003 \001(\r\022\016\n\006he"
  "ight\030\004 \001(\r\";\n\010PBRCache\022/\n\rtexture_pools\030"
  "\001 \003(\0132\030.gl.pbr.data.TexturePool*q\n\013Textu"
  "reType\022\027\n\023TEXTURE_TYPE_ALBEDO\020\000\022\025\n\021TEXTU"
  "RE_TYPE_MRAO\020\001\022\027\n\023TEXTURE_TYPE_NORMAL\020\002\022"
  "\031\n\025TEXTURE_TYPE_EMISSIVE\020\003b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_pbr_5fmeta_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_pbr_5fmeta_2eproto = {
    false, false, 314, descriptor_table_protodef_pbr_5fmeta_2eproto,
    "pbr_meta.proto",
    &descriptor_table_pbr_5fmeta_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_pbr_5fmeta_2eproto::offsets,
    file_level_metadata_pbr_5fmeta_2eproto, file_level_enum_descriptors_pbr_5fmeta_2eproto,
    file_level_service_descriptors_pbr_5fmeta_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_pbr_5fmeta_2eproto_getter() {
  return &descriptor_table_pbr_5fmeta_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_pbr_5fmeta_2eproto(&descriptor_table_pbr_5fmeta_2eproto);
namespace gl {
namespace pbr {
namespace data {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TextureType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_pbr_5fmeta_2eproto);
  return file_level_enum_descriptors_pbr_5fmeta_2eproto[0];
}
bool TextureType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class TexturePool::_Internal {
 public:
};

TexturePool::TexturePool(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:gl.pbr.data.TexturePool)
}
TexturePool::TexturePool(const TexturePool& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TexturePool* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.type_){}
    , decltype(_impl_.depth_){}
    , decltype(_impl_.width_){}
    , decltype(_impl_.height_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.type_, &from._impl_.type_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.height_) -
    reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.height_));
  // @@protoc_insertion_point(copy_constructor:gl.pbr.data.TexturePool)
}

inline void TexturePool::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.type_){0}
    , decltype(_impl_.depth_){0u}
    , decltype(_impl_.width_){0u}
    , decltype(_impl_.height_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

TexturePool::~TexturePool() {
  // @@protoc_insertion_point(destructor:gl.pbr.data.TexturePool)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TexturePool::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void TexturePool::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TexturePool::Clear() {
// @@protoc_insertion_point(message_clear_start:gl.pbr.data.TexturePool)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.height_) -
      reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.height_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TexturePool::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .gl.pbr.data.TextureType type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::gl::pbr::data::TextureType>(val));
        } else
          goto handle_unusual;
        continue;
      // uint32 depth = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.depth_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 width = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.width_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 height = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.height_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TexturePool::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:gl.pbr.data.TexturePool)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .gl.pbr.data.TextureType type = 1;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_type(), target);
  }

  // uint32 depth = 2;
  if (this->_internal_depth() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_depth(), target);
  }

  // uint32 width = 3;
  if (this->_internal_width() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_width(), target);
  }

  // uint32 height = 4;
  if (this->_internal_height() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_height(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gl.pbr.data.TexturePool)
  return target;
}

size_t TexturePool::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gl.pbr.data.TexturePool)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .gl.pbr.data.TextureType type = 1;
  if (this->_internal_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  // uint32 depth = 2;
  if (this->_internal_depth() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_depth());
  }

  // uint32 width = 3;
  if (this->_internal_width() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_width());
  }

  // uint32 height = 4;
  if (this->_internal_height() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_height());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TexturePool::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TexturePool::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TexturePool::GetClassData() const { return &_class_data_; }


void TexturePool::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TexturePool*>(&to_msg);
  auto& from = static_cast<const TexturePool&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gl.pbr.data.TexturePool)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  if (from._internal_depth() != 0) {
    _this->_internal_set_depth(from._internal_depth());
  }
  if (from._internal_width() != 0) {
    _this->_internal_set_width(from._internal_width());
  }
  if (from._internal_height() != 0) {
    _this->_internal_set_height(from._internal_height());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TexturePool::CopyFrom(const TexturePool& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gl.pbr.data.TexturePool)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TexturePool::IsInitialized() const {
  return true;
}

void TexturePool::InternalSwap(TexturePool* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TexturePool, _impl_.height_)
      + sizeof(TexturePool::_impl_.height_)
      - PROTOBUF_FIELD_OFFSET(TexturePool, _impl_.type_)>(
          reinterpret_cast<char*>(&_impl_.type_),
          reinterpret_cast<char*>(&other->_impl_.type_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TexturePool::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_pbr_5fmeta_2eproto_getter, &descriptor_table_pbr_5fmeta_2eproto_once,
      file_level_metadata_pbr_5fmeta_2eproto[0]);
}

// ===================================================================

class PBRCache::_Internal {
 public:
};

PBRCache::PBRCache(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:gl.pbr.data.PBRCache)
}
PBRCache::PBRCache(const PBRCache& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PBRCache* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.texture_pools_){from._impl_.texture_pools_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:gl.pbr.data.PBRCache)
}

inline void PBRCache::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.texture_pools_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PBRCache::~PBRCache() {
  // @@protoc_insertion_point(destructor:gl.pbr.data.PBRCache)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PBRCache::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.texture_pools_.~RepeatedPtrField();
}

void PBRCache::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PBRCache::Clear() {
// @@protoc_insertion_point(message_clear_start:gl.pbr.data.PBRCache)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.texture_pools_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PBRCache::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .gl.pbr.data.TexturePool texture_pools = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_texture_pools(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PBRCache::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:gl.pbr.data.PBRCache)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .gl.pbr.data.TexturePool texture_pools = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_texture_pools_size()); i < n; i++) {
    const auto& repfield = this->_internal_texture_pools(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gl.pbr.data.PBRCache)
  return target;
}

size_t PBRCache::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gl.pbr.data.PBRCache)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .gl.pbr.data.TexturePool texture_pools = 1;
  total_size += 1UL * this->_internal_texture_pools_size();
  for (const auto& msg : this->_impl_.texture_pools_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PBRCache::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PBRCache::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PBRCache::GetClassData() const { return &_class_data_; }


void PBRCache::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PBRCache*>(&to_msg);
  auto& from = static_cast<const PBRCache&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gl.pbr.data.PBRCache)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.texture_pools_.MergeFrom(from._impl_.texture_pools_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PBRCache::CopyFrom(const PBRCache& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gl.pbr.data.PBRCache)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBRCache::IsInitialized() const {
  return true;
}

void PBRCache::InternalSwap(PBRCache* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.texture_pools_.InternalSwap(&other->_impl_.texture_pools_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PBRCache::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_pbr_5fmeta_2eproto_getter, &descriptor_table_pbr_5fmeta_2eproto_once,
      file_level_metadata_pbr_5fmeta_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace data
}  // namespace pbr
}  // namespace gl
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::gl::pbr::data::TexturePool*
Arena::CreateMaybeMessage< ::gl::pbr::data::TexturePool >(Arena* arena) {
  return Arena::CreateMessageInternal< ::gl::pbr::data::TexturePool >(arena);
}
template<> PROTOBUF_NOINLINE ::gl::pbr::data::PBRCache*
Arena::CreateMaybeMessage< ::gl::pbr::data::PBRCache >(Arena* arena) {
  return Arena::CreateMessageInternal< ::gl::pbr::data::PBRCache >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
