// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shader.proto

#include "shader.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace gl {
PROTOBUF_CONSTEXPR ShaderEntry::ShaderEntry(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.source_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.stage_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ShaderEntryDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ShaderEntryDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ShaderEntryDefaultTypeInternal() {}
  union {
    ShaderEntry _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ShaderEntryDefaultTypeInternal _ShaderEntry_default_instance_;
PROTOBUF_CONSTEXPR ShaderFile::ShaderFile(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.shaders_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ShaderFileDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ShaderFileDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ShaderFileDefaultTypeInternal() {}
  union {
    ShaderFile _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ShaderFileDefaultTypeInternal _ShaderFile_default_instance_;
}  // namespace gl
static ::_pb::Metadata file_level_metadata_shader_2eproto[2];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_shader_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_shader_2eproto = nullptr;

const uint32_t TableStruct_shader_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::gl::ShaderEntry, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::gl::ShaderEntry, _impl_.stage_),
  PROTOBUF_FIELD_OFFSET(::gl::ShaderEntry, _impl_.source_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::gl::ShaderFile, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::gl::ShaderFile, _impl_.shaders_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::gl::ShaderEntry)},
  { 8, -1, -1, sizeof(::gl::ShaderFile)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::gl::_ShaderEntry_default_instance_._instance,
  &::gl::_ShaderFile_default_instance_._instance,
};

const char descriptor_table_protodef_shader_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014shader.proto\022\002gl\"=\n\013ShaderEntry\022\036\n\005sta"
  "ge\030\001 \001(\0162\017.gl.ShaderStage\022\016\n\006source\030\002 \001("
  "\t\".\n\nShaderFile\022 \n\007shaders\030\001 \003(\0132\017.gl.Sh"
  "aderEntry*\261\001\n\013ShaderStage\022\027\n\023SHADER_STAG"
  "E_VERTEX\020\000\022\031\n\025SHADER_STAGE_FRAGMENT\020\001\022\030\n"
  "\024SHADER_STAGE_COMPUTE\020\002\022\031\n\025SHADER_STAGE_"
  "GEOMETRY\020\003\022\035\n\031SHADER_STAGE_TESS_CONTROL\020"
  "\004\022\032\n\026SHADER_STAGE_TESS_EVAL\020\005b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_shader_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_shader_2eproto = {
    false, false, 317, descriptor_table_protodef_shader_2eproto,
    "shader.proto",
    &descriptor_table_shader_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_shader_2eproto::offsets,
    file_level_metadata_shader_2eproto, file_level_enum_descriptors_shader_2eproto,
    file_level_service_descriptors_shader_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_shader_2eproto_getter() {
  return &descriptor_table_shader_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_shader_2eproto(&descriptor_table_shader_2eproto);
namespace gl {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ShaderStage_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_shader_2eproto);
  return file_level_enum_descriptors_shader_2eproto[0];
}
bool ShaderStage_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class ShaderEntry::_Internal {
 public:
};

ShaderEntry::ShaderEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:gl.ShaderEntry)
}
ShaderEntry::ShaderEntry(const ShaderEntry& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ShaderEntry* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.source_){}
    , decltype(_impl_.stage_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.source_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.source_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_source().empty()) {
    _this->_impl_.source_.Set(from._internal_source(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.stage_ = from._impl_.stage_;
  // @@protoc_insertion_point(copy_constructor:gl.ShaderEntry)
}

inline void ShaderEntry::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.source_){}
    , decltype(_impl_.stage_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.source_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.source_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ShaderEntry::~ShaderEntry() {
  // @@protoc_insertion_point(destructor:gl.ShaderEntry)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ShaderEntry::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.source_.Destroy();
}

void ShaderEntry::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ShaderEntry::Clear() {
// @@protoc_insertion_point(message_clear_start:gl.ShaderEntry)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.source_.ClearToEmpty();
  _impl_.stage_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ShaderEntry::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .gl.ShaderStage stage = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_stage(static_cast<::gl::ShaderStage>(val));
        } else
          goto handle_unusual;
        continue;
      // string source = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_source();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "gl.ShaderEntry.source"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ShaderEntry::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:gl.ShaderEntry)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .gl.ShaderStage stage = 1;
  if (this->_internal_stage() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_stage(), target);
  }

  // string source = 2;
  if (!this->_internal_source().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_source().data(), static_cast<int>(this->_internal_source().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "gl.ShaderEntry.source");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_source(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gl.ShaderEntry)
  return target;
}

size_t ShaderEntry::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gl.ShaderEntry)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string source = 2;
  if (!this->_internal_source().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_source());
  }

  // .gl.ShaderStage stage = 1;
  if (this->_internal_stage() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_stage());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ShaderEntry::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ShaderEntry::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ShaderEntry::GetClassData() const { return &_class_data_; }


void ShaderEntry::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ShaderEntry*>(&to_msg);
  auto& from = static_cast<const ShaderEntry&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gl.ShaderEntry)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_source().empty()) {
    _this->_internal_set_source(from._internal_source());
  }
  if (from._internal_stage() != 0) {
    _this->_internal_set_stage(from._internal_stage());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ShaderEntry::CopyFrom(const ShaderEntry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gl.ShaderEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ShaderEntry::IsInitialized() const {
  return true;
}

void ShaderEntry::InternalSwap(ShaderEntry* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.source_, lhs_arena,
      &other->_impl_.source_, rhs_arena
  );
  swap(_impl_.stage_, other->_impl_.stage_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ShaderEntry::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_shader_2eproto_getter, &descriptor_table_shader_2eproto_once,
      file_level_metadata_shader_2eproto[0]);
}

// ===================================================================

class ShaderFile::_Internal {
 public:
};

ShaderFile::ShaderFile(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:gl.ShaderFile)
}
ShaderFile::ShaderFile(const ShaderFile& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ShaderFile* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.shaders_){from._impl_.shaders_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:gl.ShaderFile)
}

inline void ShaderFile::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.shaders_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ShaderFile::~ShaderFile() {
  // @@protoc_insertion_point(destructor:gl.ShaderFile)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ShaderFile::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.shaders_.~RepeatedPtrField();
}

void ShaderFile::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ShaderFile::Clear() {
// @@protoc_insertion_point(message_clear_start:gl.ShaderFile)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.shaders_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ShaderFile::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .gl.ShaderEntry shaders = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_shaders(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ShaderFile::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:gl.ShaderFile)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .gl.ShaderEntry shaders = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_shaders_size()); i < n; i++) {
    const auto& repfield = this->_internal_shaders(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gl.ShaderFile)
  return target;
}

size_t ShaderFile::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gl.ShaderFile)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .gl.ShaderEntry shaders = 1;
  total_size += 1UL * this->_internal_shaders_size();
  for (const auto& msg : this->_impl_.shaders_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ShaderFile::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ShaderFile::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ShaderFile::GetClassData() const { return &_class_data_; }


void ShaderFile::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ShaderFile*>(&to_msg);
  auto& from = static_cast<const ShaderFile&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gl.ShaderFile)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.shaders_.MergeFrom(from._impl_.shaders_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ShaderFile::CopyFrom(const ShaderFile& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gl.ShaderFile)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ShaderFile::IsInitialized() const {
  return true;
}

void ShaderFile::InternalSwap(ShaderFile* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.shaders_.InternalSwap(&other->_impl_.shaders_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ShaderFile::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_shader_2eproto_getter, &descriptor_table_shader_2eproto_once,
      file_level_metadata_shader_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace gl
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::gl::ShaderEntry*
Arena::CreateMaybeMessage< ::gl::ShaderEntry >(Arena* arena) {
  return Arena::CreateMessageInternal< ::gl::ShaderEntry >(arena);
}
template<> PROTOBUF_NOINLINE ::gl::ShaderFile*
Arena::CreateMaybeMessage< ::gl::ShaderFile >(Arena* arena) {
  return Arena::CreateMessageInternal< ::gl::ShaderFile >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
