// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DEBUGPRIMITIVES_GL_DEBUG_H_
#define FLATBUFFERS_GENERATED_DEBUGPRIMITIVES_GL_DEBUG_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace gl {
namespace debug {

struct DebugPrimitiveModel;
struct DebugPrimitiveModelBuilder;

struct DebugPrimitiveVertex;
struct DebugPrimitiveVertexBuilder;

struct DebugPrimitives;
struct DebugPrimitivesBuilder;

struct DebugPrimitiveModel FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DebugPrimitiveModelBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERT_OFFSET = 4,
    VT_EBO_OFFSET = 6,
    VT_VERT_LENGTH = 8,
    VT_EBO_LENGTH = 10
  };
  uint32_t vert_offset() const {
    return GetField<uint32_t>(VT_VERT_OFFSET, 0);
  }
  uint32_t ebo_offset() const {
    return GetField<uint32_t>(VT_EBO_OFFSET, 0);
  }
  uint32_t vert_length() const {
    return GetField<uint32_t>(VT_VERT_LENGTH, 0);
  }
  uint32_t ebo_length() const {
    return GetField<uint32_t>(VT_EBO_LENGTH, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_VERT_OFFSET, 4) &&
           VerifyField<uint32_t>(verifier, VT_EBO_OFFSET, 4) &&
           VerifyField<uint32_t>(verifier, VT_VERT_LENGTH, 4) &&
           VerifyField<uint32_t>(verifier, VT_EBO_LENGTH, 4) &&
           verifier.EndTable();
  }
};

struct DebugPrimitiveModelBuilder {
  typedef DebugPrimitiveModel Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_vert_offset(uint32_t vert_offset) {
    fbb_.AddElement<uint32_t>(DebugPrimitiveModel::VT_VERT_OFFSET, vert_offset, 0);
  }
  void add_ebo_offset(uint32_t ebo_offset) {
    fbb_.AddElement<uint32_t>(DebugPrimitiveModel::VT_EBO_OFFSET, ebo_offset, 0);
  }
  void add_vert_length(uint32_t vert_length) {
    fbb_.AddElement<uint32_t>(DebugPrimitiveModel::VT_VERT_LENGTH, vert_length, 0);
  }
  void add_ebo_length(uint32_t ebo_length) {
    fbb_.AddElement<uint32_t>(DebugPrimitiveModel::VT_EBO_LENGTH, ebo_length, 0);
  }
  explicit DebugPrimitiveModelBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DebugPrimitiveModel> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DebugPrimitiveModel>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DebugPrimitiveModel> CreateDebugPrimitiveModel(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t vert_offset = 0,
    uint32_t ebo_offset = 0,
    uint32_t vert_length = 0,
    uint32_t ebo_length = 0) {
  DebugPrimitiveModelBuilder builder_(_fbb);
  builder_.add_ebo_length(ebo_length);
  builder_.add_vert_length(vert_length);
  builder_.add_ebo_offset(ebo_offset);
  builder_.add_vert_offset(vert_offset);
  return builder_.Finish();
}

struct DebugPrimitiveVertex FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DebugPrimitiveVertexBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POSITION = 4,
    VT_NORMAL = 6
  };
  const ::flatbuffers::Vector<float> *position() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_POSITION);
  }
  const ::flatbuffers::Vector<float> *normal() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_NORMAL);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_POSITION) &&
           verifier.VerifyVector(position()) &&
           VerifyOffset(verifier, VT_NORMAL) &&
           verifier.VerifyVector(normal()) &&
           verifier.EndTable();
  }
};

struct DebugPrimitiveVertexBuilder {
  typedef DebugPrimitiveVertex Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_position(::flatbuffers::Offset<::flatbuffers::Vector<float>> position) {
    fbb_.AddOffset(DebugPrimitiveVertex::VT_POSITION, position);
  }
  void add_normal(::flatbuffers::Offset<::flatbuffers::Vector<float>> normal) {
    fbb_.AddOffset(DebugPrimitiveVertex::VT_NORMAL, normal);
  }
  explicit DebugPrimitiveVertexBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DebugPrimitiveVertex> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DebugPrimitiveVertex>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DebugPrimitiveVertex> CreateDebugPrimitiveVertex(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> position = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> normal = 0) {
  DebugPrimitiveVertexBuilder builder_(_fbb);
  builder_.add_normal(normal);
  builder_.add_position(position);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DebugPrimitiveVertex> CreateDebugPrimitiveVertexDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<float> *position = nullptr,
    const std::vector<float> *normal = nullptr) {
  auto position__ = position ? _fbb.CreateVector<float>(*position) : 0;
  auto normal__ = normal ? _fbb.CreateVector<float>(*normal) : 0;
  return gl::debug::CreateDebugPrimitiveVertex(
      _fbb,
      position__,
      normal__);
}

struct DebugPrimitives FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DebugPrimitivesBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MODEL_NAMES = 4,
    VT_MODEL_OFFSETS = 6,
    VT_VERTICES = 8,
    VT_INDICES = 10
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *model_names() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_MODEL_NAMES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<gl::debug::DebugPrimitiveModel>> *model_offsets() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<gl::debug::DebugPrimitiveModel>> *>(VT_MODEL_OFFSETS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<gl::debug::DebugPrimitiveVertex>> *vertices() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<gl::debug::DebugPrimitiveVertex>> *>(VT_VERTICES);
  }
  const ::flatbuffers::Vector<uint32_t> *indices() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_INDICES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MODEL_NAMES) &&
           verifier.VerifyVector(model_names()) &&
           verifier.VerifyVectorOfStrings(model_names()) &&
           VerifyOffset(verifier, VT_MODEL_OFFSETS) &&
           verifier.VerifyVector(model_offsets()) &&
           verifier.VerifyVectorOfTables(model_offsets()) &&
           VerifyOffset(verifier, VT_VERTICES) &&
           verifier.VerifyVector(vertices()) &&
           verifier.VerifyVectorOfTables(vertices()) &&
           VerifyOffset(verifier, VT_INDICES) &&
           verifier.VerifyVector(indices()) &&
           verifier.EndTable();
  }
};

struct DebugPrimitivesBuilder {
  typedef DebugPrimitives Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_model_names(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> model_names) {
    fbb_.AddOffset(DebugPrimitives::VT_MODEL_NAMES, model_names);
  }
  void add_model_offsets(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<gl::debug::DebugPrimitiveModel>>> model_offsets) {
    fbb_.AddOffset(DebugPrimitives::VT_MODEL_OFFSETS, model_offsets);
  }
  void add_vertices(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<gl::debug::DebugPrimitiveVertex>>> vertices) {
    fbb_.AddOffset(DebugPrimitives::VT_VERTICES, vertices);
  }
  void add_indices(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> indices) {
    fbb_.AddOffset(DebugPrimitives::VT_INDICES, indices);
  }
  explicit DebugPrimitivesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DebugPrimitives> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DebugPrimitives>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DebugPrimitives> CreateDebugPrimitives(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> model_names = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<gl::debug::DebugPrimitiveModel>>> model_offsets = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<gl::debug::DebugPrimitiveVertex>>> vertices = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> indices = 0) {
  DebugPrimitivesBuilder builder_(_fbb);
  builder_.add_indices(indices);
  builder_.add_vertices(vertices);
  builder_.add_model_offsets(model_offsets);
  builder_.add_model_names(model_names);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DebugPrimitives> CreateDebugPrimitivesDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *model_names = nullptr,
    const std::vector<::flatbuffers::Offset<gl::debug::DebugPrimitiveModel>> *model_offsets = nullptr,
    const std::vector<::flatbuffers::Offset<gl::debug::DebugPrimitiveVertex>> *vertices = nullptr,
    const std::vector<uint32_t> *indices = nullptr) {
  auto model_names__ = model_names ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*model_names) : 0;
  auto model_offsets__ = model_offsets ? _fbb.CreateVector<::flatbuffers::Offset<gl::debug::DebugPrimitiveModel>>(*model_offsets) : 0;
  auto vertices__ = vertices ? _fbb.CreateVector<::flatbuffers::Offset<gl::debug::DebugPrimitiveVertex>>(*vertices) : 0;
  auto indices__ = indices ? _fbb.CreateVector<uint32_t>(*indices) : 0;
  return gl::debug::CreateDebugPrimitives(
      _fbb,
      model_names__,
      model_offsets__,
      vertices__,
      indices__);
}

inline const gl::debug::DebugPrimitives *GetDebugPrimitives(const void *buf) {
  return ::flatbuffers::GetRoot<gl::debug::DebugPrimitives>(buf);
}

inline const gl::debug::DebugPrimitives *GetSizePrefixedDebugPrimitives(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<gl::debug::DebugPrimitives>(buf);
}

inline bool VerifyDebugPrimitivesBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<gl::debug::DebugPrimitives>(nullptr);
}

inline bool VerifySizePrefixedDebugPrimitivesBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<gl::debug::DebugPrimitives>(nullptr);
}

inline void FinishDebugPrimitivesBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<gl::debug::DebugPrimitives> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedDebugPrimitivesBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<gl::debug::DebugPrimitives> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace debug
}  // namespace gl

#endif  // FLATBUFFERS_GENERATED_DEBUGPRIMITIVES_GL_DEBUG_H_
