// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: debug_primitives.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_debug_5fprimitives_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_debug_5fprimitives_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_debug_5fprimitives_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_debug_5fprimitives_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_debug_5fprimitives_2eproto;
namespace gl {
namespace debug {
class DebugPrimitiveModel;
struct DebugPrimitiveModelDefaultTypeInternal;
extern DebugPrimitiveModelDefaultTypeInternal _DebugPrimitiveModel_default_instance_;
class DebugPrimitiveVertex;
struct DebugPrimitiveVertexDefaultTypeInternal;
extern DebugPrimitiveVertexDefaultTypeInternal _DebugPrimitiveVertex_default_instance_;
class DebugPrimitives;
struct DebugPrimitivesDefaultTypeInternal;
extern DebugPrimitivesDefaultTypeInternal _DebugPrimitives_default_instance_;
}  // namespace debug
}  // namespace gl
PROTOBUF_NAMESPACE_OPEN
template<> ::gl::debug::DebugPrimitiveModel* Arena::CreateMaybeMessage<::gl::debug::DebugPrimitiveModel>(Arena*);
template<> ::gl::debug::DebugPrimitiveVertex* Arena::CreateMaybeMessage<::gl::debug::DebugPrimitiveVertex>(Arena*);
template<> ::gl::debug::DebugPrimitives* Arena::CreateMaybeMessage<::gl::debug::DebugPrimitives>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace gl {
namespace debug {

// ===================================================================

class DebugPrimitiveModel final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gl.debug.DebugPrimitiveModel) */ {
 public:
  inline DebugPrimitiveModel() : DebugPrimitiveModel(nullptr) {}
  ~DebugPrimitiveModel() override;
  explicit PROTOBUF_CONSTEXPR DebugPrimitiveModel(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DebugPrimitiveModel(const DebugPrimitiveModel& from);
  DebugPrimitiveModel(DebugPrimitiveModel&& from) noexcept
    : DebugPrimitiveModel() {
    *this = ::std::move(from);
  }

  inline DebugPrimitiveModel& operator=(const DebugPrimitiveModel& from) {
    CopyFrom(from);
    return *this;
  }
  inline DebugPrimitiveModel& operator=(DebugPrimitiveModel&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DebugPrimitiveModel& default_instance() {
    return *internal_default_instance();
  }
  static inline const DebugPrimitiveModel* internal_default_instance() {
    return reinterpret_cast<const DebugPrimitiveModel*>(
               &_DebugPrimitiveModel_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DebugPrimitiveModel& a, DebugPrimitiveModel& b) {
    a.Swap(&b);
  }
  inline void Swap(DebugPrimitiveModel* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DebugPrimitiveModel* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DebugPrimitiveModel* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DebugPrimitiveModel>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DebugPrimitiveModel& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DebugPrimitiveModel& from) {
    DebugPrimitiveModel::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DebugPrimitiveModel* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gl.debug.DebugPrimitiveModel";
  }
  protected:
  explicit DebugPrimitiveModel(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVertOffsetFieldNumber = 1,
    kEboOffsetFieldNumber = 2,
    kVertLengthFieldNumber = 3,
    kEboLengthFieldNumber = 4,
  };
  // uint32 vert_offset = 1;
  void clear_vert_offset();
  uint32_t vert_offset() const;
  void set_vert_offset(uint32_t value);
  private:
  uint32_t _internal_vert_offset() const;
  void _internal_set_vert_offset(uint32_t value);
  public:

  // uint32 ebo_offset = 2;
  void clear_ebo_offset();
  uint32_t ebo_offset() const;
  void set_ebo_offset(uint32_t value);
  private:
  uint32_t _internal_ebo_offset() const;
  void _internal_set_ebo_offset(uint32_t value);
  public:

  // uint32 vert_length = 3;
  void clear_vert_length();
  uint32_t vert_length() const;
  void set_vert_length(uint32_t value);
  private:
  uint32_t _internal_vert_length() const;
  void _internal_set_vert_length(uint32_t value);
  public:

  // uint32 ebo_length = 4;
  void clear_ebo_length();
  uint32_t ebo_length() const;
  void set_ebo_length(uint32_t value);
  private:
  uint32_t _internal_ebo_length() const;
  void _internal_set_ebo_length(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:gl.debug.DebugPrimitiveModel)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t vert_offset_;
    uint32_t ebo_offset_;
    uint32_t vert_length_;
    uint32_t ebo_length_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_debug_5fprimitives_2eproto;
};
// -------------------------------------------------------------------

class DebugPrimitiveVertex final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gl.debug.DebugPrimitiveVertex) */ {
 public:
  inline DebugPrimitiveVertex() : DebugPrimitiveVertex(nullptr) {}
  ~DebugPrimitiveVertex() override;
  explicit PROTOBUF_CONSTEXPR DebugPrimitiveVertex(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DebugPrimitiveVertex(const DebugPrimitiveVertex& from);
  DebugPrimitiveVertex(DebugPrimitiveVertex&& from) noexcept
    : DebugPrimitiveVertex() {
    *this = ::std::move(from);
  }

  inline DebugPrimitiveVertex& operator=(const DebugPrimitiveVertex& from) {
    CopyFrom(from);
    return *this;
  }
  inline DebugPrimitiveVertex& operator=(DebugPrimitiveVertex&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DebugPrimitiveVertex& default_instance() {
    return *internal_default_instance();
  }
  static inline const DebugPrimitiveVertex* internal_default_instance() {
    return reinterpret_cast<const DebugPrimitiveVertex*>(
               &_DebugPrimitiveVertex_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(DebugPrimitiveVertex& a, DebugPrimitiveVertex& b) {
    a.Swap(&b);
  }
  inline void Swap(DebugPrimitiveVertex* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DebugPrimitiveVertex* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DebugPrimitiveVertex* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DebugPrimitiveVertex>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DebugPrimitiveVertex& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DebugPrimitiveVertex& from) {
    DebugPrimitiveVertex::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DebugPrimitiveVertex* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gl.debug.DebugPrimitiveVertex";
  }
  protected:
  explicit DebugPrimitiveVertex(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPositionFieldNumber = 1,
    kNormalFieldNumber = 2,
  };
  // repeated float position = 1;
  int position_size() const;
  private:
  int _internal_position_size() const;
  public:
  void clear_position();
  private:
  float _internal_position(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_position() const;
  void _internal_add_position(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_position();
  public:
  float position(int index) const;
  void set_position(int index, float value);
  void add_position(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      position() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_position();

  // repeated float normal = 2;
  int normal_size() const;
  private:
  int _internal_normal_size() const;
  public:
  void clear_normal();
  private:
  float _internal_normal(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_normal() const;
  void _internal_add_normal(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_normal();
  public:
  float normal(int index) const;
  void set_normal(int index, float value);
  void add_normal(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      normal() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_normal();

  // @@protoc_insertion_point(class_scope:gl.debug.DebugPrimitiveVertex)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > position_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > normal_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_debug_5fprimitives_2eproto;
};
// -------------------------------------------------------------------

class DebugPrimitives final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gl.debug.DebugPrimitives) */ {
 public:
  inline DebugPrimitives() : DebugPrimitives(nullptr) {}
  ~DebugPrimitives() override;
  explicit PROTOBUF_CONSTEXPR DebugPrimitives(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DebugPrimitives(const DebugPrimitives& from);
  DebugPrimitives(DebugPrimitives&& from) noexcept
    : DebugPrimitives() {
    *this = ::std::move(from);
  }

  inline DebugPrimitives& operator=(const DebugPrimitives& from) {
    CopyFrom(from);
    return *this;
  }
  inline DebugPrimitives& operator=(DebugPrimitives&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DebugPrimitives& default_instance() {
    return *internal_default_instance();
  }
  static inline const DebugPrimitives* internal_default_instance() {
    return reinterpret_cast<const DebugPrimitives*>(
               &_DebugPrimitives_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(DebugPrimitives& a, DebugPrimitives& b) {
    a.Swap(&b);
  }
  inline void Swap(DebugPrimitives* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DebugPrimitives* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DebugPrimitives* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DebugPrimitives>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DebugPrimitives& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DebugPrimitives& from) {
    DebugPrimitives::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DebugPrimitives* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gl.debug.DebugPrimitives";
  }
  protected:
  explicit DebugPrimitives(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kModelNamesFieldNumber = 1,
    kModelOffsetsFieldNumber = 2,
    kVerticesFieldNumber = 3,
    kIndicesFieldNumber = 4,
  };
  // repeated string model_names = 1;
  int model_names_size() const;
  private:
  int _internal_model_names_size() const;
  public:
  void clear_model_names();
  const std::string& model_names(int index) const;
  std::string* mutable_model_names(int index);
  void set_model_names(int index, const std::string& value);
  void set_model_names(int index, std::string&& value);
  void set_model_names(int index, const char* value);
  void set_model_names(int index, const char* value, size_t size);
  std::string* add_model_names();
  void add_model_names(const std::string& value);
  void add_model_names(std::string&& value);
  void add_model_names(const char* value);
  void add_model_names(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& model_names() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_model_names();
  private:
  const std::string& _internal_model_names(int index) const;
  std::string* _internal_add_model_names();
  public:

  // repeated .gl.debug.DebugPrimitiveModel model_offsets = 2;
  int model_offsets_size() const;
  private:
  int _internal_model_offsets_size() const;
  public:
  void clear_model_offsets();
  ::gl::debug::DebugPrimitiveModel* mutable_model_offsets(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gl::debug::DebugPrimitiveModel >*
      mutable_model_offsets();
  private:
  const ::gl::debug::DebugPrimitiveModel& _internal_model_offsets(int index) const;
  ::gl::debug::DebugPrimitiveModel* _internal_add_model_offsets();
  public:
  const ::gl::debug::DebugPrimitiveModel& model_offsets(int index) const;
  ::gl::debug::DebugPrimitiveModel* add_model_offsets();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gl::debug::DebugPrimitiveModel >&
      model_offsets() const;

  // repeated .gl.debug.DebugPrimitiveVertex vertices = 3;
  int vertices_size() const;
  private:
  int _internal_vertices_size() const;
  public:
  void clear_vertices();
  ::gl::debug::DebugPrimitiveVertex* mutable_vertices(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gl::debug::DebugPrimitiveVertex >*
      mutable_vertices();
  private:
  const ::gl::debug::DebugPrimitiveVertex& _internal_vertices(int index) const;
  ::gl::debug::DebugPrimitiveVertex* _internal_add_vertices();
  public:
  const ::gl::debug::DebugPrimitiveVertex& vertices(int index) const;
  ::gl::debug::DebugPrimitiveVertex* add_vertices();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gl::debug::DebugPrimitiveVertex >&
      vertices() const;

  // repeated uint32 indices = 4;
  int indices_size() const;
  private:
  int _internal_indices_size() const;
  public:
  void clear_indices();
  private:
  uint32_t _internal_indices(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
      _internal_indices() const;
  void _internal_add_indices(uint32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
      _internal_mutable_indices();
  public:
  uint32_t indices(int index) const;
  void set_indices(int index, uint32_t value);
  void add_indices(uint32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
      indices() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
      mutable_indices();

  // @@protoc_insertion_point(class_scope:gl.debug.DebugPrimitives)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> model_names_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gl::debug::DebugPrimitiveModel > model_offsets_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gl::debug::DebugPrimitiveVertex > vertices_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t > indices_;
    mutable std::atomic<int> _indices_cached_byte_size_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_debug_5fprimitives_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DebugPrimitiveModel

// uint32 vert_offset = 1;
inline void DebugPrimitiveModel::clear_vert_offset() {
  _impl_.vert_offset_ = 0u;
}
inline uint32_t DebugPrimitiveModel::_internal_vert_offset() const {
  return _impl_.vert_offset_;
}
inline uint32_t DebugPrimitiveModel::vert_offset() const {
  // @@protoc_insertion_point(field_get:gl.debug.DebugPrimitiveModel.vert_offset)
  return _internal_vert_offset();
}
inline void DebugPrimitiveModel::_internal_set_vert_offset(uint32_t value) {
  
  _impl_.vert_offset_ = value;
}
inline void DebugPrimitiveModel::set_vert_offset(uint32_t value) {
  _internal_set_vert_offset(value);
  // @@protoc_insertion_point(field_set:gl.debug.DebugPrimitiveModel.vert_offset)
}

// uint32 ebo_offset = 2;
inline void DebugPrimitiveModel::clear_ebo_offset() {
  _impl_.ebo_offset_ = 0u;
}
inline uint32_t DebugPrimitiveModel::_internal_ebo_offset() const {
  return _impl_.ebo_offset_;
}
inline uint32_t DebugPrimitiveModel::ebo_offset() const {
  // @@protoc_insertion_point(field_get:gl.debug.DebugPrimitiveModel.ebo_offset)
  return _internal_ebo_offset();
}
inline void DebugPrimitiveModel::_internal_set_ebo_offset(uint32_t value) {
  
  _impl_.ebo_offset_ = value;
}
inline void DebugPrimitiveModel::set_ebo_offset(uint32_t value) {
  _internal_set_ebo_offset(value);
  // @@protoc_insertion_point(field_set:gl.debug.DebugPrimitiveModel.ebo_offset)
}

// uint32 vert_length = 3;
inline void DebugPrimitiveModel::clear_vert_length() {
  _impl_.vert_length_ = 0u;
}
inline uint32_t DebugPrimitiveModel::_internal_vert_length() const {
  return _impl_.vert_length_;
}
inline uint32_t DebugPrimitiveModel::vert_length() const {
  // @@protoc_insertion_point(field_get:gl.debug.DebugPrimitiveModel.vert_length)
  return _internal_vert_length();
}
inline void DebugPrimitiveModel::_internal_set_vert_length(uint32_t value) {
  
  _impl_.vert_length_ = value;
}
inline void DebugPrimitiveModel::set_vert_length(uint32_t value) {
  _internal_set_vert_length(value);
  // @@protoc_insertion_point(field_set:gl.debug.DebugPrimitiveModel.vert_length)
}

// uint32 ebo_length = 4;
inline void DebugPrimitiveModel::clear_ebo_length() {
  _impl_.ebo_length_ = 0u;
}
inline uint32_t DebugPrimitiveModel::_internal_ebo_length() const {
  return _impl_.ebo_length_;
}
inline uint32_t DebugPrimitiveModel::ebo_length() const {
  // @@protoc_insertion_point(field_get:gl.debug.DebugPrimitiveModel.ebo_length)
  return _internal_ebo_length();
}
inline void DebugPrimitiveModel::_internal_set_ebo_length(uint32_t value) {
  
  _impl_.ebo_length_ = value;
}
inline void DebugPrimitiveModel::set_ebo_length(uint32_t value) {
  _internal_set_ebo_length(value);
  // @@protoc_insertion_point(field_set:gl.debug.DebugPrimitiveModel.ebo_length)
}

// -------------------------------------------------------------------

// DebugPrimitiveVertex

// repeated float position = 1;
inline int DebugPrimitiveVertex::_internal_position_size() const {
  return _impl_.position_.size();
}
inline int DebugPrimitiveVertex::position_size() const {
  return _internal_position_size();
}
inline void DebugPrimitiveVertex::clear_position() {
  _impl_.position_.Clear();
}
inline float DebugPrimitiveVertex::_internal_position(int index) const {
  return _impl_.position_.Get(index);
}
inline float DebugPrimitiveVertex::position(int index) const {
  // @@protoc_insertion_point(field_get:gl.debug.DebugPrimitiveVertex.position)
  return _internal_position(index);
}
inline void DebugPrimitiveVertex::set_position(int index, float value) {
  _impl_.position_.Set(index, value);
  // @@protoc_insertion_point(field_set:gl.debug.DebugPrimitiveVertex.position)
}
inline void DebugPrimitiveVertex::_internal_add_position(float value) {
  _impl_.position_.Add(value);
}
inline void DebugPrimitiveVertex::add_position(float value) {
  _internal_add_position(value);
  // @@protoc_insertion_point(field_add:gl.debug.DebugPrimitiveVertex.position)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
DebugPrimitiveVertex::_internal_position() const {
  return _impl_.position_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
DebugPrimitiveVertex::position() const {
  // @@protoc_insertion_point(field_list:gl.debug.DebugPrimitiveVertex.position)
  return _internal_position();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
DebugPrimitiveVertex::_internal_mutable_position() {
  return &_impl_.position_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
DebugPrimitiveVertex::mutable_position() {
  // @@protoc_insertion_point(field_mutable_list:gl.debug.DebugPrimitiveVertex.position)
  return _internal_mutable_position();
}

// repeated float normal = 2;
inline int DebugPrimitiveVertex::_internal_normal_size() const {
  return _impl_.normal_.size();
}
inline int DebugPrimitiveVertex::normal_size() const {
  return _internal_normal_size();
}
inline void DebugPrimitiveVertex::clear_normal() {
  _impl_.normal_.Clear();
}
inline float DebugPrimitiveVertex::_internal_normal(int index) const {
  return _impl_.normal_.Get(index);
}
inline float DebugPrimitiveVertex::normal(int index) const {
  // @@protoc_insertion_point(field_get:gl.debug.DebugPrimitiveVertex.normal)
  return _internal_normal(index);
}
inline void DebugPrimitiveVertex::set_normal(int index, float value) {
  _impl_.normal_.Set(index, value);
  // @@protoc_insertion_point(field_set:gl.debug.DebugPrimitiveVertex.normal)
}
inline void DebugPrimitiveVertex::_internal_add_normal(float value) {
  _impl_.normal_.Add(value);
}
inline void DebugPrimitiveVertex::add_normal(float value) {
  _internal_add_normal(value);
  // @@protoc_insertion_point(field_add:gl.debug.DebugPrimitiveVertex.normal)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
DebugPrimitiveVertex::_internal_normal() const {
  return _impl_.normal_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
DebugPrimitiveVertex::normal() const {
  // @@protoc_insertion_point(field_list:gl.debug.DebugPrimitiveVertex.normal)
  return _internal_normal();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
DebugPrimitiveVertex::_internal_mutable_normal() {
  return &_impl_.normal_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
DebugPrimitiveVertex::mutable_normal() {
  // @@protoc_insertion_point(field_mutable_list:gl.debug.DebugPrimitiveVertex.normal)
  return _internal_mutable_normal();
}

// -------------------------------------------------------------------

// DebugPrimitives

// repeated string model_names = 1;
inline int DebugPrimitives::_internal_model_names_size() const {
  return _impl_.model_names_.size();
}
inline int DebugPrimitives::model_names_size() const {
  return _internal_model_names_size();
}
inline void DebugPrimitives::clear_model_names() {
  _impl_.model_names_.Clear();
}
inline std::string* DebugPrimitives::add_model_names() {
  std::string* _s = _internal_add_model_names();
  // @@protoc_insertion_point(field_add_mutable:gl.debug.DebugPrimitives.model_names)
  return _s;
}
inline const std::string& DebugPrimitives::_internal_model_names(int index) const {
  return _impl_.model_names_.Get(index);
}
inline const std::string& DebugPrimitives::model_names(int index) const {
  // @@protoc_insertion_point(field_get:gl.debug.DebugPrimitives.model_names)
  return _internal_model_names(index);
}
inline std::string* DebugPrimitives::mutable_model_names(int index) {
  // @@protoc_insertion_point(field_mutable:gl.debug.DebugPrimitives.model_names)
  return _impl_.model_names_.Mutable(index);
}
inline void DebugPrimitives::set_model_names(int index, const std::string& value) {
  _impl_.model_names_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:gl.debug.DebugPrimitives.model_names)
}
inline void DebugPrimitives::set_model_names(int index, std::string&& value) {
  _impl_.model_names_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:gl.debug.DebugPrimitives.model_names)
}
inline void DebugPrimitives::set_model_names(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.model_names_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:gl.debug.DebugPrimitives.model_names)
}
inline void DebugPrimitives::set_model_names(int index, const char* value, size_t size) {
  _impl_.model_names_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:gl.debug.DebugPrimitives.model_names)
}
inline std::string* DebugPrimitives::_internal_add_model_names() {
  return _impl_.model_names_.Add();
}
inline void DebugPrimitives::add_model_names(const std::string& value) {
  _impl_.model_names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:gl.debug.DebugPrimitives.model_names)
}
inline void DebugPrimitives::add_model_names(std::string&& value) {
  _impl_.model_names_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:gl.debug.DebugPrimitives.model_names)
}
inline void DebugPrimitives::add_model_names(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.model_names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:gl.debug.DebugPrimitives.model_names)
}
inline void DebugPrimitives::add_model_names(const char* value, size_t size) {
  _impl_.model_names_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:gl.debug.DebugPrimitives.model_names)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
DebugPrimitives::model_names() const {
  // @@protoc_insertion_point(field_list:gl.debug.DebugPrimitives.model_names)
  return _impl_.model_names_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
DebugPrimitives::mutable_model_names() {
  // @@protoc_insertion_point(field_mutable_list:gl.debug.DebugPrimitives.model_names)
  return &_impl_.model_names_;
}

// repeated .gl.debug.DebugPrimitiveModel model_offsets = 2;
inline int DebugPrimitives::_internal_model_offsets_size() const {
  return _impl_.model_offsets_.size();
}
inline int DebugPrimitives::model_offsets_size() const {
  return _internal_model_offsets_size();
}
inline void DebugPrimitives::clear_model_offsets() {
  _impl_.model_offsets_.Clear();
}
inline ::gl::debug::DebugPrimitiveModel* DebugPrimitives::mutable_model_offsets(int index) {
  // @@protoc_insertion_point(field_mutable:gl.debug.DebugPrimitives.model_offsets)
  return _impl_.model_offsets_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gl::debug::DebugPrimitiveModel >*
DebugPrimitives::mutable_model_offsets() {
  // @@protoc_insertion_point(field_mutable_list:gl.debug.DebugPrimitives.model_offsets)
  return &_impl_.model_offsets_;
}
inline const ::gl::debug::DebugPrimitiveModel& DebugPrimitives::_internal_model_offsets(int index) const {
  return _impl_.model_offsets_.Get(index);
}
inline const ::gl::debug::DebugPrimitiveModel& DebugPrimitives::model_offsets(int index) const {
  // @@protoc_insertion_point(field_get:gl.debug.DebugPrimitives.model_offsets)
  return _internal_model_offsets(index);
}
inline ::gl::debug::DebugPrimitiveModel* DebugPrimitives::_internal_add_model_offsets() {
  return _impl_.model_offsets_.Add();
}
inline ::gl::debug::DebugPrimitiveModel* DebugPrimitives::add_model_offsets() {
  ::gl::debug::DebugPrimitiveModel* _add = _internal_add_model_offsets();
  // @@protoc_insertion_point(field_add:gl.debug.DebugPrimitives.model_offsets)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gl::debug::DebugPrimitiveModel >&
DebugPrimitives::model_offsets() const {
  // @@protoc_insertion_point(field_list:gl.debug.DebugPrimitives.model_offsets)
  return _impl_.model_offsets_;
}

// repeated .gl.debug.DebugPrimitiveVertex vertices = 3;
inline int DebugPrimitives::_internal_vertices_size() const {
  return _impl_.vertices_.size();
}
inline int DebugPrimitives::vertices_size() const {
  return _internal_vertices_size();
}
inline void DebugPrimitives::clear_vertices() {
  _impl_.vertices_.Clear();
}
inline ::gl::debug::DebugPrimitiveVertex* DebugPrimitives::mutable_vertices(int index) {
  // @@protoc_insertion_point(field_mutable:gl.debug.DebugPrimitives.vertices)
  return _impl_.vertices_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gl::debug::DebugPrimitiveVertex >*
DebugPrimitives::mutable_vertices() {
  // @@protoc_insertion_point(field_mutable_list:gl.debug.DebugPrimitives.vertices)
  return &_impl_.vertices_;
}
inline const ::gl::debug::DebugPrimitiveVertex& DebugPrimitives::_internal_vertices(int index) const {
  return _impl_.vertices_.Get(index);
}
inline const ::gl::debug::DebugPrimitiveVertex& DebugPrimitives::vertices(int index) const {
  // @@protoc_insertion_point(field_get:gl.debug.DebugPrimitives.vertices)
  return _internal_vertices(index);
}
inline ::gl::debug::DebugPrimitiveVertex* DebugPrimitives::_internal_add_vertices() {
  return _impl_.vertices_.Add();
}
inline ::gl::debug::DebugPrimitiveVertex* DebugPrimitives::add_vertices() {
  ::gl::debug::DebugPrimitiveVertex* _add = _internal_add_vertices();
  // @@protoc_insertion_point(field_add:gl.debug.DebugPrimitives.vertices)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gl::debug::DebugPrimitiveVertex >&
DebugPrimitives::vertices() const {
  // @@protoc_insertion_point(field_list:gl.debug.DebugPrimitives.vertices)
  return _impl_.vertices_;
}

// repeated uint32 indices = 4;
inline int DebugPrimitives::_internal_indices_size() const {
  return _impl_.indices_.size();
}
inline int DebugPrimitives::indices_size() const {
  return _internal_indices_size();
}
inline void DebugPrimitives::clear_indices() {
  _impl_.indices_.Clear();
}
inline uint32_t DebugPrimitives::_internal_indices(int index) const {
  return _impl_.indices_.Get(index);
}
inline uint32_t DebugPrimitives::indices(int index) const {
  // @@protoc_insertion_point(field_get:gl.debug.DebugPrimitives.indices)
  return _internal_indices(index);
}
inline void DebugPrimitives::set_indices(int index, uint32_t value) {
  _impl_.indices_.Set(index, value);
  // @@protoc_insertion_point(field_set:gl.debug.DebugPrimitives.indices)
}
inline void DebugPrimitives::_internal_add_indices(uint32_t value) {
  _impl_.indices_.Add(value);
}
inline void DebugPrimitives::add_indices(uint32_t value) {
  _internal_add_indices(value);
  // @@protoc_insertion_point(field_add:gl.debug.DebugPrimitives.indices)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
DebugPrimitives::_internal_indices() const {
  return _impl_.indices_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
DebugPrimitives::indices() const {
  // @@protoc_insertion_point(field_list:gl.debug.DebugPrimitives.indices)
  return _internal_indices();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
DebugPrimitives::_internal_mutable_indices() {
  return &_impl_.indices_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
DebugPrimitives::mutable_indices() {
  // @@protoc_insertion_point(field_mutable_list:gl.debug.DebugPrimitives.indices)
  return _internal_mutable_indices();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace debug
}  // namespace gl

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_debug_5fprimitives_2eproto
