// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbr_meta.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_pbr_5fmeta_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_pbr_5fmeta_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_pbr_5fmeta_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_pbr_5fmeta_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_pbr_5fmeta_2eproto;
namespace gl {
namespace pbr {
namespace data {
class PBRCache;
struct PBRCacheDefaultTypeInternal;
extern PBRCacheDefaultTypeInternal _PBRCache_default_instance_;
class TexturePool;
struct TexturePoolDefaultTypeInternal;
extern TexturePoolDefaultTypeInternal _TexturePool_default_instance_;
}  // namespace data
}  // namespace pbr
}  // namespace gl
PROTOBUF_NAMESPACE_OPEN
template<> ::gl::pbr::data::PBRCache* Arena::CreateMaybeMessage<::gl::pbr::data::PBRCache>(Arena*);
template<> ::gl::pbr::data::TexturePool* Arena::CreateMaybeMessage<::gl::pbr::data::TexturePool>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace gl {
namespace pbr {
namespace data {

enum TextureType : int {
  TEXTURE_TYPE_ALBEDO = 0,
  TEXTURE_TYPE_MRAO = 1,
  TEXTURE_TYPE_NORMAL = 2,
  TEXTURE_TYPE_EMISSIVE = 3,
  TextureType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  TextureType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool TextureType_IsValid(int value);
constexpr TextureType TextureType_MIN = TEXTURE_TYPE_ALBEDO;
constexpr TextureType TextureType_MAX = TEXTURE_TYPE_EMISSIVE;
constexpr int TextureType_ARRAYSIZE = TextureType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TextureType_descriptor();
template<typename T>
inline const std::string& TextureType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, TextureType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function TextureType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    TextureType_descriptor(), enum_t_value);
}
inline bool TextureType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, TextureType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<TextureType>(
    TextureType_descriptor(), name, value);
}
// ===================================================================

class TexturePool final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gl.pbr.data.TexturePool) */ {
 public:
  inline TexturePool() : TexturePool(nullptr) {}
  ~TexturePool() override;
  explicit PROTOBUF_CONSTEXPR TexturePool(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TexturePool(const TexturePool& from);
  TexturePool(TexturePool&& from) noexcept
    : TexturePool() {
    *this = ::std::move(from);
  }

  inline TexturePool& operator=(const TexturePool& from) {
    CopyFrom(from);
    return *this;
  }
  inline TexturePool& operator=(TexturePool&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TexturePool& default_instance() {
    return *internal_default_instance();
  }
  static inline const TexturePool* internal_default_instance() {
    return reinterpret_cast<const TexturePool*>(
               &_TexturePool_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TexturePool& a, TexturePool& b) {
    a.Swap(&b);
  }
  inline void Swap(TexturePool* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TexturePool* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TexturePool* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TexturePool>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TexturePool& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TexturePool& from) {
    TexturePool::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TexturePool* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gl.pbr.data.TexturePool";
  }
  protected:
  explicit TexturePool(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTypeFieldNumber = 1,
    kDepthFieldNumber = 2,
    kWidthFieldNumber = 3,
    kHeightFieldNumber = 4,
  };
  // .gl.pbr.data.TextureType type = 1;
  void clear_type();
  ::gl::pbr::data::TextureType type() const;
  void set_type(::gl::pbr::data::TextureType value);
  private:
  ::gl::pbr::data::TextureType _internal_type() const;
  void _internal_set_type(::gl::pbr::data::TextureType value);
  public:

  // uint32 depth = 2;
  void clear_depth();
  uint32_t depth() const;
  void set_depth(uint32_t value);
  private:
  uint32_t _internal_depth() const;
  void _internal_set_depth(uint32_t value);
  public:

  // uint32 width = 3;
  void clear_width();
  uint32_t width() const;
  void set_width(uint32_t value);
  private:
  uint32_t _internal_width() const;
  void _internal_set_width(uint32_t value);
  public:

  // uint32 height = 4;
  void clear_height();
  uint32_t height() const;
  void set_height(uint32_t value);
  private:
  uint32_t _internal_height() const;
  void _internal_set_height(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:gl.pbr.data.TexturePool)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int type_;
    uint32_t depth_;
    uint32_t width_;
    uint32_t height_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_pbr_5fmeta_2eproto;
};
// -------------------------------------------------------------------

class PBRCache final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gl.pbr.data.PBRCache) */ {
 public:
  inline PBRCache() : PBRCache(nullptr) {}
  ~PBRCache() override;
  explicit PROTOBUF_CONSTEXPR PBRCache(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PBRCache(const PBRCache& from);
  PBRCache(PBRCache&& from) noexcept
    : PBRCache() {
    *this = ::std::move(from);
  }

  inline PBRCache& operator=(const PBRCache& from) {
    CopyFrom(from);
    return *this;
  }
  inline PBRCache& operator=(PBRCache&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PBRCache& default_instance() {
    return *internal_default_instance();
  }
  static inline const PBRCache* internal_default_instance() {
    return reinterpret_cast<const PBRCache*>(
               &_PBRCache_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PBRCache& a, PBRCache& b) {
    a.Swap(&b);
  }
  inline void Swap(PBRCache* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PBRCache* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PBRCache* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PBRCache>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PBRCache& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PBRCache& from) {
    PBRCache::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PBRCache* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gl.pbr.data.PBRCache";
  }
  protected:
  explicit PBRCache(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTexturePoolsFieldNumber = 1,
  };
  // repeated .gl.pbr.data.TexturePool texture_pools = 1;
  int texture_pools_size() const;
  private:
  int _internal_texture_pools_size() const;
  public:
  void clear_texture_pools();
  ::gl::pbr::data::TexturePool* mutable_texture_pools(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gl::pbr::data::TexturePool >*
      mutable_texture_pools();
  private:
  const ::gl::pbr::data::TexturePool& _internal_texture_pools(int index) const;
  ::gl::pbr::data::TexturePool* _internal_add_texture_pools();
  public:
  const ::gl::pbr::data::TexturePool& texture_pools(int index) const;
  ::gl::pbr::data::TexturePool* add_texture_pools();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gl::pbr::data::TexturePool >&
      texture_pools() const;

  // @@protoc_insertion_point(class_scope:gl.pbr.data.PBRCache)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gl::pbr::data::TexturePool > texture_pools_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_pbr_5fmeta_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TexturePool

// .gl.pbr.data.TextureType type = 1;
inline void TexturePool::clear_type() {
  _impl_.type_ = 0;
}
inline ::gl::pbr::data::TextureType TexturePool::_internal_type() const {
  return static_cast< ::gl::pbr::data::TextureType >(_impl_.type_);
}
inline ::gl::pbr::data::TextureType TexturePool::type() const {
  // @@protoc_insertion_point(field_get:gl.pbr.data.TexturePool.type)
  return _internal_type();
}
inline void TexturePool::_internal_set_type(::gl::pbr::data::TextureType value) {
  
  _impl_.type_ = value;
}
inline void TexturePool::set_type(::gl::pbr::data::TextureType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:gl.pbr.data.TexturePool.type)
}

// uint32 depth = 2;
inline void TexturePool::clear_depth() {
  _impl_.depth_ = 0u;
}
inline uint32_t TexturePool::_internal_depth() const {
  return _impl_.depth_;
}
inline uint32_t TexturePool::depth() const {
  // @@protoc_insertion_point(field_get:gl.pbr.data.TexturePool.depth)
  return _internal_depth();
}
inline void TexturePool::_internal_set_depth(uint32_t value) {
  
  _impl_.depth_ = value;
}
inline void TexturePool::set_depth(uint32_t value) {
  _internal_set_depth(value);
  // @@protoc_insertion_point(field_set:gl.pbr.data.TexturePool.depth)
}

// uint32 width = 3;
inline void TexturePool::clear_width() {
  _impl_.width_ = 0u;
}
inline uint32_t TexturePool::_internal_width() const {
  return _impl_.width_;
}
inline uint32_t TexturePool::width() const {
  // @@protoc_insertion_point(field_get:gl.pbr.data.TexturePool.width)
  return _internal_width();
}
inline void TexturePool::_internal_set_width(uint32_t value) {
  
  _impl_.width_ = value;
}
inline void TexturePool::set_width(uint32_t value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:gl.pbr.data.TexturePool.width)
}

// uint32 height = 4;
inline void TexturePool::clear_height() {
  _impl_.height_ = 0u;
}
inline uint32_t TexturePool::_internal_height() const {
  return _impl_.height_;
}
inline uint32_t TexturePool::height() const {
  // @@protoc_insertion_point(field_get:gl.pbr.data.TexturePool.height)
  return _internal_height();
}
inline void TexturePool::_internal_set_height(uint32_t value) {
  
  _impl_.height_ = value;
}
inline void TexturePool::set_height(uint32_t value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:gl.pbr.data.TexturePool.height)
}

// -------------------------------------------------------------------

// PBRCache

// repeated .gl.pbr.data.TexturePool texture_pools = 1;
inline int PBRCache::_internal_texture_pools_size() const {
  return _impl_.texture_pools_.size();
}
inline int PBRCache::texture_pools_size() const {
  return _internal_texture_pools_size();
}
inline void PBRCache::clear_texture_pools() {
  _impl_.texture_pools_.Clear();
}
inline ::gl::pbr::data::TexturePool* PBRCache::mutable_texture_pools(int index) {
  // @@protoc_insertion_point(field_mutable:gl.pbr.data.PBRCache.texture_pools)
  return _impl_.texture_pools_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gl::pbr::data::TexturePool >*
PBRCache::mutable_texture_pools() {
  // @@protoc_insertion_point(field_mutable_list:gl.pbr.data.PBRCache.texture_pools)
  return &_impl_.texture_pools_;
}
inline const ::gl::pbr::data::TexturePool& PBRCache::_internal_texture_pools(int index) const {
  return _impl_.texture_pools_.Get(index);
}
inline const ::gl::pbr::data::TexturePool& PBRCache::texture_pools(int index) const {
  // @@protoc_insertion_point(field_get:gl.pbr.data.PBRCache.texture_pools)
  return _internal_texture_pools(index);
}
inline ::gl::pbr::data::TexturePool* PBRCache::_internal_add_texture_pools() {
  return _impl_.texture_pools_.Add();
}
inline ::gl::pbr::data::TexturePool* PBRCache::add_texture_pools() {
  ::gl::pbr::data::TexturePool* _add = _internal_add_texture_pools();
  // @@protoc_insertion_point(field_add:gl.pbr.data.PBRCache.texture_pools)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gl::pbr::data::TexturePool >&
PBRCache::texture_pools() const {
  // @@protoc_insertion_point(field_list:gl.pbr.data.PBRCache.texture_pools)
  return _impl_.texture_pools_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace data
}  // namespace pbr
}  // namespace gl

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::gl::pbr::data::TextureType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::gl::pbr::data::TextureType>() {
  return ::gl::pbr::data::TextureType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_pbr_5fmeta_2eproto
