// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shader.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_shader_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_shader_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_shader_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_shader_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_shader_2eproto;
namespace gl {
class ShaderEntry;
struct ShaderEntryDefaultTypeInternal;
extern ShaderEntryDefaultTypeInternal _ShaderEntry_default_instance_;
class ShaderFile;
struct ShaderFileDefaultTypeInternal;
extern ShaderFileDefaultTypeInternal _ShaderFile_default_instance_;
}  // namespace gl
PROTOBUF_NAMESPACE_OPEN
template<> ::gl::ShaderEntry* Arena::CreateMaybeMessage<::gl::ShaderEntry>(Arena*);
template<> ::gl::ShaderFile* Arena::CreateMaybeMessage<::gl::ShaderFile>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace gl {

enum ShaderStage : int {
  SHADER_STAGE_VERTEX = 0,
  SHADER_STAGE_FRAGMENT = 1,
  SHADER_STAGE_COMPUTE = 2,
  SHADER_STAGE_GEOMETRY = 3,
  SHADER_STAGE_TESS_CONTROL = 4,
  SHADER_STAGE_TESS_EVAL = 5,
  ShaderStage_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ShaderStage_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ShaderStage_IsValid(int value);
constexpr ShaderStage ShaderStage_MIN = SHADER_STAGE_VERTEX;
constexpr ShaderStage ShaderStage_MAX = SHADER_STAGE_TESS_EVAL;
constexpr int ShaderStage_ARRAYSIZE = ShaderStage_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ShaderStage_descriptor();
template<typename T>
inline const std::string& ShaderStage_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ShaderStage>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ShaderStage_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ShaderStage_descriptor(), enum_t_value);
}
inline bool ShaderStage_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ShaderStage* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ShaderStage>(
    ShaderStage_descriptor(), name, value);
}
// ===================================================================

class ShaderEntry final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gl.ShaderEntry) */ {
 public:
  inline ShaderEntry() : ShaderEntry(nullptr) {}
  ~ShaderEntry() override;
  explicit PROTOBUF_CONSTEXPR ShaderEntry(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ShaderEntry(const ShaderEntry& from);
  ShaderEntry(ShaderEntry&& from) noexcept
    : ShaderEntry() {
    *this = ::std::move(from);
  }

  inline ShaderEntry& operator=(const ShaderEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline ShaderEntry& operator=(ShaderEntry&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ShaderEntry& default_instance() {
    return *internal_default_instance();
  }
  static inline const ShaderEntry* internal_default_instance() {
    return reinterpret_cast<const ShaderEntry*>(
               &_ShaderEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ShaderEntry& a, ShaderEntry& b) {
    a.Swap(&b);
  }
  inline void Swap(ShaderEntry* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ShaderEntry* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ShaderEntry* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ShaderEntry>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ShaderEntry& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ShaderEntry& from) {
    ShaderEntry::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ShaderEntry* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gl.ShaderEntry";
  }
  protected:
  explicit ShaderEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSourceFieldNumber = 2,
    kStageFieldNumber = 1,
  };
  // string source = 2;
  void clear_source();
  const std::string& source() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_source(ArgT0&& arg0, ArgT... args);
  std::string* mutable_source();
  PROTOBUF_NODISCARD std::string* release_source();
  void set_allocated_source(std::string* source);
  private:
  const std::string& _internal_source() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_source(const std::string& value);
  std::string* _internal_mutable_source();
  public:

  // .gl.ShaderStage stage = 1;
  void clear_stage();
  ::gl::ShaderStage stage() const;
  void set_stage(::gl::ShaderStage value);
  private:
  ::gl::ShaderStage _internal_stage() const;
  void _internal_set_stage(::gl::ShaderStage value);
  public:

  // @@protoc_insertion_point(class_scope:gl.ShaderEntry)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr source_;
    int stage_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_shader_2eproto;
};
// -------------------------------------------------------------------

class ShaderFile final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gl.ShaderFile) */ {
 public:
  inline ShaderFile() : ShaderFile(nullptr) {}
  ~ShaderFile() override;
  explicit PROTOBUF_CONSTEXPR ShaderFile(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ShaderFile(const ShaderFile& from);
  ShaderFile(ShaderFile&& from) noexcept
    : ShaderFile() {
    *this = ::std::move(from);
  }

  inline ShaderFile& operator=(const ShaderFile& from) {
    CopyFrom(from);
    return *this;
  }
  inline ShaderFile& operator=(ShaderFile&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ShaderFile& default_instance() {
    return *internal_default_instance();
  }
  static inline const ShaderFile* internal_default_instance() {
    return reinterpret_cast<const ShaderFile*>(
               &_ShaderFile_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ShaderFile& a, ShaderFile& b) {
    a.Swap(&b);
  }
  inline void Swap(ShaderFile* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ShaderFile* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ShaderFile* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ShaderFile>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ShaderFile& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ShaderFile& from) {
    ShaderFile::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ShaderFile* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gl.ShaderFile";
  }
  protected:
  explicit ShaderFile(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kShadersFieldNumber = 1,
  };
  // repeated .gl.ShaderEntry shaders = 1;
  int shaders_size() const;
  private:
  int _internal_shaders_size() const;
  public:
  void clear_shaders();
  ::gl::ShaderEntry* mutable_shaders(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gl::ShaderEntry >*
      mutable_shaders();
  private:
  const ::gl::ShaderEntry& _internal_shaders(int index) const;
  ::gl::ShaderEntry* _internal_add_shaders();
  public:
  const ::gl::ShaderEntry& shaders(int index) const;
  ::gl::ShaderEntry* add_shaders();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gl::ShaderEntry >&
      shaders() const;

  // @@protoc_insertion_point(class_scope:gl.ShaderFile)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gl::ShaderEntry > shaders_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_shader_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ShaderEntry

// .gl.ShaderStage stage = 1;
inline void ShaderEntry::clear_stage() {
  _impl_.stage_ = 0;
}
inline ::gl::ShaderStage ShaderEntry::_internal_stage() const {
  return static_cast< ::gl::ShaderStage >(_impl_.stage_);
}
inline ::gl::ShaderStage ShaderEntry::stage() const {
  // @@protoc_insertion_point(field_get:gl.ShaderEntry.stage)
  return _internal_stage();
}
inline void ShaderEntry::_internal_set_stage(::gl::ShaderStage value) {
  
  _impl_.stage_ = value;
}
inline void ShaderEntry::set_stage(::gl::ShaderStage value) {
  _internal_set_stage(value);
  // @@protoc_insertion_point(field_set:gl.ShaderEntry.stage)
}

// string source = 2;
inline void ShaderEntry::clear_source() {
  _impl_.source_.ClearToEmpty();
}
inline const std::string& ShaderEntry::source() const {
  // @@protoc_insertion_point(field_get:gl.ShaderEntry.source)
  return _internal_source();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ShaderEntry::set_source(ArgT0&& arg0, ArgT... args) {
 
 _impl_.source_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:gl.ShaderEntry.source)
}
inline std::string* ShaderEntry::mutable_source() {
  std::string* _s = _internal_mutable_source();
  // @@protoc_insertion_point(field_mutable:gl.ShaderEntry.source)
  return _s;
}
inline const std::string& ShaderEntry::_internal_source() const {
  return _impl_.source_.Get();
}
inline void ShaderEntry::_internal_set_source(const std::string& value) {
  
  _impl_.source_.Set(value, GetArenaForAllocation());
}
inline std::string* ShaderEntry::_internal_mutable_source() {
  
  return _impl_.source_.Mutable(GetArenaForAllocation());
}
inline std::string* ShaderEntry::release_source() {
  // @@protoc_insertion_point(field_release:gl.ShaderEntry.source)
  return _impl_.source_.Release();
}
inline void ShaderEntry::set_allocated_source(std::string* source) {
  if (source != nullptr) {
    
  } else {
    
  }
  _impl_.source_.SetAllocated(source, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.source_.IsDefault()) {
    _impl_.source_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:gl.ShaderEntry.source)
}

// -------------------------------------------------------------------

// ShaderFile

// repeated .gl.ShaderEntry shaders = 1;
inline int ShaderFile::_internal_shaders_size() const {
  return _impl_.shaders_.size();
}
inline int ShaderFile::shaders_size() const {
  return _internal_shaders_size();
}
inline void ShaderFile::clear_shaders() {
  _impl_.shaders_.Clear();
}
inline ::gl::ShaderEntry* ShaderFile::mutable_shaders(int index) {
  // @@protoc_insertion_point(field_mutable:gl.ShaderFile.shaders)
  return _impl_.shaders_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gl::ShaderEntry >*
ShaderFile::mutable_shaders() {
  // @@protoc_insertion_point(field_mutable_list:gl.ShaderFile.shaders)
  return &_impl_.shaders_;
}
inline const ::gl::ShaderEntry& ShaderFile::_internal_shaders(int index) const {
  return _impl_.shaders_.Get(index);
}
inline const ::gl::ShaderEntry& ShaderFile::shaders(int index) const {
  // @@protoc_insertion_point(field_get:gl.ShaderFile.shaders)
  return _internal_shaders(index);
}
inline ::gl::ShaderEntry* ShaderFile::_internal_add_shaders() {
  return _impl_.shaders_.Add();
}
inline ::gl::ShaderEntry* ShaderFile::add_shaders() {
  ::gl::ShaderEntry* _add = _internal_add_shaders();
  // @@protoc_insertion_point(field_add:gl.ShaderFile.shaders)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gl::ShaderEntry >&
ShaderFile::shaders() const {
  // @@protoc_insertion_point(field_list:gl.ShaderFile.shaders)
  return _impl_.shaders_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace gl

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::gl::ShaderStage> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::gl::ShaderStage>() {
  return ::gl::ShaderStage_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_shader_2eproto
